/**
* FileName: VipInfomationConst.java
* @Description: 描述VIP支付相关的常量
* All rights Reserved, Designed By 21winmess
* Copyright: Copyright(C) 2010-2011 
* Company 21winmess DaLian LTD.
* @author: Allan Zhang
* @version V1.3
* Createdate: 2012-10-29 下午03:44:55
*
* Modification History:
* Date Author Version Discription
* -----------------------------------------------------------------------------------
* 2012-10-29 Qute_Android2.0
* Why & What is modified: <修改原因描述>
*/
package com.tencent.onesecurity.manager.vip;

/**
 * @ClassName: VipInfomationConst
 * @Description:描述VIP支付相关的常量
 * @author: Allan
 * @date: 2012-10-29 下午03:44:55
 *
 */
public class VipInfomationConst {	
	//支付状态
	public static final int paymentPayNone = 0;
	public static final int paymentPayBegin = 1;
	public static final int paymentPayInprocessing = 2;
	public static final int paymentPayCommit = 3;
	public static final int paymentPayNetError = 4;
	public static final int paymentPayFail = 5;
	public static final int paymentPaySuceess = 6;
	public static final int paymentPayMopayUnknown = 7;
	
	//Mopay SDK SSL证书的有效期
	public static final long mopaySslValidTimeMin = 1262275200000L;//2010.01.01
	public static final long mopaySslValidTimeMax = 1388505600000L;//2014.01.01
	
	//采用的支付方式
	public static final int payModeNone = 0;
	public static final int payModeMopay = 1;		//Mopay支付
	public static final int payModePaypal = 2;		//Paypal支付
	public static final int payModeGoogleWallet = 3;		//Google Wallet
	
	//注册过程的状态
	public static final String paymentActionPayFailed = "payment_pay_failed";
	public static final String paymentActionPayGetStatus = "payment_pay_get_status";
	public static final String paymentActionPaySuccess = "payment_pay_success";
	public static final String paymentActionMopayProcessing = "payment_mopay_processing";
	public static final String paymentOpenTrialSucc = "payment_open_trial_succ";
	public static final String paymentOpenTrialFailed = "payment_open_trial_failed";
	public static final String paymentOpenTrialNetError = "payment_open_trial_net_error";
	
	//Mopay使用的参数
	public static final String paymentMopayButtonID = "payment_mopay_button_id";
	public static final String paymentMopayMyID = "payment_mopay_my_id";
	public static final String paymentMopayCountry = "payment_mopay_country";
	public static final String paymentMopayTime = "payment_mopay_time";
	public static final String paymentMopayTariffKey = "payment_mopay_tariff_key";
	public static final String paymentMopayStartMode = "payment_mopay_start_mode";
	static final int paymentMopayModeTariffKey = 1;
	public static final int paymentMopayModeButtonId = 2;
	
	public static String paymentJspSuccess = "success_n.jsp";
	public static String paymentJspFail = "fail_n.jsp";
	public static String paymentJspProcessing = "process.jsp";
	public static String paymentJspUserCancel = "cancel.jsp";
	public static String paymentJspMopayMode = "mopayreturn.jsp";
	public static String paymentJspMopayLoading = "mopay.jsp";
	public static String paymentJspJumpToPaypal = "paypal.com";
	public static String paymentJspPaypalCommit = "paypalcommit.jsp";
	public static String paymentJspTrialQuestionnaire = "trail_gateway.jsp";
	public static String paymentJspTrialQuestionnaireSuccess = "trail_success.jsp";
	
	//语言编码
	//public static final int LANG_AalandIsland = "AX";
	public static final int LANG_Azerbaijan = 2092;//	AZE	2092	阿塞拜疆
	public static final int LANG_BosniaHerzegovina = 3098;//	BIH	3098	波黑
	//public static final int LANG_Barbados = "BB";
	//public static final int LANG_Bangladesh = "BD";
	public static final int LANG_Belgium = 1059;//BEL	1059	比利时
	//public static final int LANG_Burkina = "BF";
	public static final int LANG_Bulgaria	= 1026;	//BGR	1026	保加利亚
	public static final int LANG_Bahrain	= 15361;	//	BHR	15361	巴林
//	public static final int LANG_Burundi	= "BI";	//	BDI		布隆迪
//	public static final int LANG_Benin	= "BJ";	//	BEN		贝宁
//	public static final int LANG_SaintBarthelemy	= "BL";	//	BLM		圣巴泰勒米岛
//	public static final int LANG_Bermuda	= "BM";	//	BMU		百慕大
	public static final int LANG_Brunei	= 2110;	//	BRN	2110	文莱
	public static final int LANG_Bolivia	= 16394;	//	BOL	16394	玻利维亚
//	public static final int LANG_CaribbeanNetherlands	= "BQ";	//	BES		荷兰加勒比区
	public static final int LANG_Brazil	= 1046;	//	BRA	1046	巴西
//	public static final int LANG_Bahamas	= "BS";	//	BHS		巴哈马
//	public static final int LANG_Bhutan	= "BT";	//	BTN		不丹
//	public static final int LANG_BouvetIsland	= "BV";	//	BVT		布韦岛
//	public static final int LANG_Botswana	= "BW";	//	BWA		博茨瓦纳
//	public static final int LANG_Belarus	= "BY";	//	BLR		白俄罗斯
	public static final int LANG_Belize	= 10249;	//	BLZ	10249	伯利兹
	public static final int LANG_Canada	= 4105;	//	CAN	4105	加拿大
//	public static final int LANG_CocosIslands	= "CC";	//	CCK		科科斯群岛
//	public static final int LANG_DemocraticRepublicoftheCongo	= "CD";	//	COD		刚果（金）
//	public static final int LANG_CentralAfricanRepublic	= "CF";	//	CAF		中非
//	public static final int LANG_RepublicoftheCongo	= "CG";	//	COG		刚果（布）
	public static final int LANG_Switzerland	= 2055;	//	CHE	2055	瑞士
//	public static final int LANG_CotedIvoire	= "CI";	//	CIV		科特迪瓦
//	public static final int LANG_CookIslands	= "CK";	//	COK		库克群岛
	public static final int LANG_Chile	= 13322;	//	CHL	13322	智利
//	public static final int LANG_Cameroon	= "CM";	//	CMR		喀麦隆
	public static final int LANG_China	= 2052;	//	CHN	2052	中国
	public static final int LANG_Colombia	= 9226;	//	COL	9226	哥伦比亚
//	public static final int LANG_CostaRica	= "CR";	//	CRI		哥斯达黎加
//	public static final int LANG_Cuba	= "CU";	//	CUB		古巴
//	public static final int LANG_CapeVerde	= "CV";	//	CPV		佛得角
//	public static final int LANG_Curacao	= "CW";	//	CUW		库拉索
//	public static final int LANG_ChristmasIsland	= "CX";	//	CXR		圣诞岛
//	public static final int LANG_Cyprus	= "CY";	//	CYP		塞浦路斯
//	public static final int LANG_CzechRepublic	= "CZ";	//	CZE		捷克
	public static final int LANG_Germany	= 1031;	//	DEU	1031	德国
//	public static final int LANG_Djibouti	= "DJ";	//	DJI		吉布提
//	public static final int LANG_Denmark	= "DK";	//	DNK		丹麦
//	public static final int LANG_Dominica	= "DM";	//	DMA		多米尼克
	public static final int LANG_DominicanRepublic	= 7178;	//	DOM	7178	多米尼加
	public static final int LANG_Algeria	= 5121;	//	DZA	5121	阿尔及利亚
	public static final int LANG_Ecuador	= 12298;	//	ECU	12298	厄瓜多尔
//	public static final int LANG_Estonia	= "EE";	//	EST		爱沙尼亚
	public static final int LANG_Egypt	= 3073;	//	EGY	3073	埃及
//	public static final int LANG_WesternSahara	= "EH";	//	ESH		西撒哈拉
//	public static final int LANG_Eritrea	= "ER";	//	ERI		厄立特里亚
	public static final int LANG_Spain	= 1034;	//	ESP	1034	西班牙
	public static final int LANG_Ethiopia	= 1061;	//	ETH	1061	埃塞俄比亚
	public static final int LANG_Finland	= 2077;	//	FIN	2077	芬兰
//	public static final int LANG_Fiji	= "FJ";	//	FJI		斐济群岛
//	public static final int LANG_FalklandIslands	= "FK";	//	FLK		马尔维纳斯群岛（福克兰）
//	public static final int LANG_FederatedStatesofMicronesia	= "FM";	//	FSM		密克罗尼西亚联邦
	public static final int LANG_FaroeIslands	= 1080;	//	FRO	1080	法罗群岛
	public static final int LANG_France	= 1036;	//	FRA	1036	法国
//	public static final int LANG_Gabon	= "GA";	//	GAB		加蓬
	public static final int LANG_GreatBritain = 2057;	//	GBR	2057	英国
//	public static final int LANG_Grenada	= "GD";	//	GRD		格林纳达
//	public static final int LANG_Georgia	= "GE";	//	GEO		格鲁吉亚
//	public static final int LANG_FrenchGuiana	= "GF";	//	GUF		法属圭亚那
//	public static final int LANG_Guernsey	= "GG";	//	GGY		根西岛
//	public static final int LANG_Ghana	= "GH";	//	GHA		加纳
//	public static final int LANG_Gibraltar	= "GI";	//	GIB		直布罗陀
//	public static final int LANG_Greenland	= "GL";	//	GRL		格陵兰
//	public static final int LANG_Gambia	= "GM";	//	GMB		冈比亚
//	public static final int LANG_Guinea	= "GN";	//	GIN		几内亚
//	public static final int LANG_Guadeloupe	= "GP";	//	GLP		瓜德罗普
//	public static final int LANG_EquatorialGuinea	= "GQ";	//	GNQ		赤道几内亚
	public static final int LANG_Greece	= 1032;	//	GRC	1032	希腊
//	public static final int LANG_SouthGeorgiaandtheSouthSandwichIslands	= "GS";	//	SGS		南乔治亚岛和南桑威奇群岛
	public static final int LANG_Guatemala	= 4106;	//	GTM	4106	危地马拉
//	public static final int LANG_Guam	= "GU";	//	GUM		关岛
//	public static final int LANG_GuineaBissau	= "GW";	//	GNB		几内亚比绍
//	public static final int LANG_Guyana	= "GY";	//	GUY		圭亚那
	public static final int LANG_HongKong	= 3076;	//	HKG	3076	香港
//	public static final int LANG_HeardIslandandMcDonaldIslands	= "HM";	//	HMD		赫德岛和麦克唐纳群岛
	public static final int LANG_Honduras	= 18442;	//	HND	18442	洪都拉斯
	public static final int LANG_Croatia	= 1050;	//	HRV	1050	克罗地亚
//	public static final int LANG_Haiti	= "HT";	//	HTI		海地
	public static final int LANG_Hungary	= 1038;	//	HUN	1038	匈牙利
	public static final int LANG_Indonesia	= 1057;	//	IDN	1057	印尼
	public static final int LANG_Ireland	= 6153;	//	IRL	6153	爱尔兰
	public static final int LANG_Israel	= 1037;	//	ISR	1037	以色列
//	public static final int LANG_IsleofMan	= "IM";	//	IMN		马恩岛
//	public static final int LANG_India	= "IN";	//	IND		印度
//	public static final int LANG_BritishIndianOceanTerritory	= "IO";	//	IOT		英属印度洋领地
	public static final int LANG_Iraq	= 2049;	//	IRQ	2049	伊拉克
//	public static final int LANG_Iran	= "IR";	//	IRN		伊朗
	public static final int LANG_Iceland	= 1039;	//	ISL	1039	冰岛
	public static final int LANG_Italy	= 1040;	//	ITA	1040	意大利
//	public static final int LANG_Jersey	= "JE";	//	JEY		泽西岛
	public static final int LANG_Jamaica	= 8201;	//	JAM	8201	牙买加
	public static final int LANG_Jordan	= 11265;	//	JOR	11265	约旦
	public static final int LANG_Japan	= 1041;	//	JPN	1041	日本
	public static final int LANG_Kenya	= 1089;	//	KEN	1089	肯尼亚
//	public static final int LANG_Kyrgyzstan	= "KG";	//	KGZ		吉尔吉斯斯坦
//	public static final int LANG_Cambodia	= "KH";	//	KHM		柬埔寨
//	public static final int LANG_Kiribati	= "KI";	//	KIR		基里巴斯
//	public static final int LANG_TheComoros	= "KM";	//	COM		科摩罗
//	public static final int LANG_StKittsNevis	= "KN";	//	KNA		圣基茨和尼维斯
//	public static final int LANG_NorthKorea	= "KP";	//	PRK		朝鲜；
	public static final int LANG_SouthKorea	= 1042;	//	KOR	1042	韩国；
	public static final int LANG_Kuwait	= 13313;	//	KWT	13313	科威特
//	public static final int LANG_CaymanIslands	= "KY";	//	CYM		开曼群岛
//	public static final int LANG_Kazakhstan	= "KZ";	//	KAZ		哈萨克斯坦
//	public static final int LANG_Laos	= "LA";	//	LAO		老挝
	public static final int LANG_Lebanon	= 12289;	//	LBN	12289	黎巴嫩
//	public static final int LANG_StLucia	= "LC";	//	LCA		圣卢西亚
	public static final int LANG_Liechtenstein	= 5127;	//	LIE	5127	列支敦士登
//	public static final int LANG_SriLanka	= "LK";	//	LKA		斯里兰卡
//	public static final int LANG_Liberia	= "LR";	//	LBR		利比里亚
//	public static final int LANG_Lesotho	= "LS";	//	LSO		莱索托
	public static final int LANG_Lithuania	= 1063;	//	LTU	1063	立陶宛
	public static final int LANG_Luxembourg	= 4103;	//	LUX	4103	卢森堡
	public static final int LANG_Latvia	= 1062;	//	LVA	1062	拉脱维亚
	public static final int LANG_Libya	= 4097;	//	LBY	4097	利比亚
	public static final int LANG_Morocco	= 6145;	//	MAR	6145	摩洛哥
//	public static final int LANG_Monaco	= "MC";	//	MCO		摩纳哥
//	public static final int LANG_Moldova	= "MD";	//	MDA		摩尔多瓦
//	public static final int LANG_Montenegro	= "ME";	//	MNE		黑山
//	public static final int LANG_SaintMartinFrance	= "MF";	//	MAF		法属圣马丁
//	public static final int LANG_Madagascar	= "MG";	//	MDG		马达加斯加
//	public static final int LANG_MarshallIslands	= "MH";	//	MHL		马绍尔群岛
	public static final int LANG_RepublicofMacedonia	= 1071;	//	MKD	1071	马其顿
//	public static final int LANG_Mali	= "ML";	//	MLI		马里
//	public static final int LANG_MyanmarBurma	= "MM";	//	MMR		缅甸
//	public static final int LANG_Mongolia	= "MN";	//	MNG		蒙古国；蒙古
	public static final int LANG_Macao	= 5124;	//	MAC	5124	澳门
//	public static final int LANG_NorthernMarianaIslands	= "MP";	//	MNP		北马里亚纳群岛
//	public static final int LANG_Martinique	= "MQ";	//	MTQ		马提尼克
//	public static final int LANG_Mauritania	= "MR";	//	MRT		毛里塔尼亚
//	public static final int LANG_Montserrat	= "MS";	//	MSR		蒙塞拉特岛
//	public static final int LANG_Malta	= "MT";	//	MLT		马耳他
//	public static final int LANG_Mauritius	= "MU";	//	MUS		毛里求斯
//	public static final int LANG_Maldives	= "MV";	//	MDV		马尔代夫
//	public static final int LANG_Malawi	= "MW";	//	MWI		马拉维
	public static final int LANG_Mexico	= 2058;	//	MEX	2058	墨西哥
	public static final int LANG_Malaysia	= 1086;	//	MYS	1086	马来西亚
//	public static final int LANG_Mozambique	= "MZ";	//	MOZ		莫桑比克
//	public static final int LANG_Namibia	= "NA";	//	NAM		纳米比亚
//	public static final int LANG_NewCaledonia	= "NC";	//	NCL		新喀里多尼亚
//	public static final int LANG_Niger	= "NE";	//	NER		尼日尔
//	public static final int LANG_NorfolkIsland	= "NF";	//	NFK		诺福克岛
//	public static final int LANG_Nigeria	= "NG";	//	NGA		尼日利亚
	public static final int LANG_Nicaragua	= 19466;	//	NIC	19466	尼加拉瓜
	public static final int LANG_Netherlands	= 1043;	//	NLD	1043	荷兰
	public static final int LANG_Norway	= 2068;	//	NOR	2068	挪威
//	public static final int LANG_Nepal	= "NP";	//	NPL		尼泊尔
//	public static final int LANG_Nauru	= "NR";	//	NRU		瑙鲁
//	public static final int LANG_Niue	= "NU";	//	NIU		纽埃
	public static final int LANG_NewZealand	= 5129;	//	NZL	5129	新西兰
	public static final int LANG_Oman	= 8193;	//	OMN	8193	阿曼
	public static final int LANG_Panama	= 6154;	//	PAN	6154	巴拿马
	public static final int LANG_Peru	= 10250;	//	PER	10250	秘鲁
//	public static final int LANG_FrenchPolynesia	= "PF";	//	PYF		法属波利尼西亚
//	public static final int LANG_PapuaNewGuinea	= "PG";	//	PNG		巴布亚新几内亚
	public static final int LANG_ThePhilippines	= 13321;	//	PHL	13321	菲律宾
	public static final int LANG_Pakistan	= 1056;	//	PAK	1056	巴基斯坦
	public static final int LANG_Poland	= 1045;	//	POL	1045	波兰
//	public static final int LANG_SaintPierreandMiquelon	= "PM";	//	SPM		圣皮埃尔和密克隆
//	public static final int LANG_PitcairnIslands	= "PN";	//	PCN		皮特凯恩群岛
	public static final int LANG_PuertoRico	= 20490;	//	PRI	20490	波多黎各
//	public static final int LANG_Palestinianterritories	= "PS";	//	PSE		巴勒斯坦
	public static final int LANG_Portugal	= 2070;	//	PRT	2070	葡萄牙
//	public static final int LANG_Palau	= "PW";	//	PLW		帕劳
	public static final int LANG_Paraguay	= 15370;	//	PRY	15370	巴拉圭
	public static final int LANG_Qatar	= 16385;	//	QAT	16385	卡塔尔
//	public static final int LANG_Reunion	= "RE";	//	REU		留尼汪
	public static final int LANG_Romania	= 1048;	//	ROU	1048	罗马尼亚
//	public static final int LANG_Serbia	= "RS";	//	SRB		塞尔维亚
	public static final int LANG_RussianFederation	= 1092;	//	RUS	1092	俄罗斯
//	public static final int LANG_Rwanda	= "RW";	//	RWA		卢旺达
	public static final int LANG_SaudiArabia	= 1025;	//	SAU	1025	沙特阿拉伯
//	public static final int LANG_SolomonIslands	= "SB";	//	SLB		所罗门群岛
//	public static final int LANG_Seychelles	= "SC";	//	SYC		塞舌尔
//	public static final int LANG_Sudan	= "SD";	//	SDN		苏丹
	public static final int LANG_Sweden	= 1053;	//	SWE	1053	瑞典
	public static final int LANG_Singapore	= 4100;	//	SGP	4100	新加坡
//	public static final int LANG_StHelenaDependencies	= "SH";	//	SHN		圣赫勒拿
//	public static final int LANG_Slovenia	= "SI";	//	SVN		斯洛文尼亚
//	public static final int LANG_TemplateLANG_dataSJMSvalbard	= "SJ";	//	SJM		斯瓦尔巴群岛和扬马延岛
	public static final int LANG_Slovakia	= 1051;	//	SVK	1051	斯洛伐克
//	public static final int LANG_SierraLeone	= "SL";	//	SLE		塞拉利昂
//	public static final int LANG_SanMarino	= "SM";	//	SMR		圣马力诺
//	public static final int LANG_Senegal	= "SN";	//	SEN		塞内加尔
//	public static final int LANG_Somalia	= "SO";	//	SOM		索马里
//	public static final int LANG_Suriname	= "SR";	//	SUR		苏里南
//	public static final int LANG_SouthSudan	= "SS";	//	SSD		南苏丹
//	public static final int LANG_SaoTomePrincipe	= "ST";	//	STP		圣多美和普林西比
	public static final int LANG_ElSalvador	= 17418;	//	SLV	17418	萨尔瓦多
//	public static final int LANG_SintMaarten	= "SX";	//	SXM		荷属圣马丁
	public static final int LANG_Syria	= 10241;	//	SYR	10241	叙利亚
//	public static final int LANG_Swaziland	= "SZ";	//	SWZ		斯威士兰
//	public static final int LANG_TurksCaicosIslands	= "TC";	//	TCA		特克斯和凯科斯群岛
//	public static final int LANG_Chad	= "TD";	//	TCD		乍得
//	public static final int LANG_FrenchSouthernTerritories	= "TF";	//	ATF		法属南部领地
//	public static final int LANG_Togo	= "TG";	//	TGO		多哥
	public static final int LANG_Thailand	= 1054;	//	THA	1054	泰国
//	public static final int LANG_Tajikistan	= "TJ";	//	TJK		塔吉克斯坦
//	public static final int LANG_Tokelau	= "TK";	//	TKL		托克劳
//	public static final int LANG_TimorLesteEastTimor	= "TL";	//	TLS		东帝汶
//	public static final int LANG_Turkmenistan	= "TM";	//	TKM		土库曼斯坦
	public static final int LANG_Tunisia	= 7169;	//	TUN	7169	突尼斯
//	public static final int LANG_Tonga	= "TO";	//	TON		汤加
	public static final int LANG_Turkey	= 1055;	//	TUR	1055	土耳其
	public static final int LANG_TrinidadTobago	= 11273;	//	TTO	11273	特立尼达和多巴哥
//	public static final int LANG_Tuvalu	= "TV";	//	TUV		图瓦卢
	public static final int LANG_Taiwan	= 1028;	//	TWN	1028	中国台湾
//	public static final int LANG_Tanzania	= "TZ";	//	TZA		坦桑尼亚
	public static final int LANG_Ukraine	= 1058;	//	UKR	1058	乌克兰
//	public static final int LANG_Uganda	= "UG";	//	UGA		乌干达
//	public static final int LANG_UnitedStatesMinorOutlyingIslands	= "UM";	//	UMI		美国本土外小岛屿
	public static final int LANG_America	= 1033;	//	USA	1033	美国
	public static final int LANG_Uruguay	= 14346;	//	URY	14346	乌拉圭
	public static final int LANG_Uzbekistan	= 2115;	//	UZB	2115	乌兹别克斯坦
//	public static final int LANG_VaticanCityTheHolySee	= "VA";	//	VAT		梵蒂冈
//	public static final int LANG_StVincenttheGrenadines	= "VC";	//	VCT		圣文森特和格林纳丁斯
	public static final int LANG_Venezuela	= 8202;	//	VEN	8202	委内瑞拉
//	public static final int LANG_BritishVirginIslands	= "VG";	//	VGB		英属维尔京群岛
//	public static final int LANG_UnitedStatesVirginIslands	= "VI";	//	VIR		美属维尔京群岛
	public static final int LANG_Vietnam	= 1066;	//	VNM	1066	越南
//	public static final int LANG_Vanuatu	= "VU";	//	VUT		瓦努阿图
//	public static final int LANG_WallisandFutuna	= "WF";	//	WLF		瓦利斯和富图纳
//	public static final int LANG_Samoa	= "WS";	//	WSM		萨摩亚
	public static final int LANG_Yemen	= 9217;	//	YEM	9217	也门
//	public static final int LANG_Mayotte	= "YT";	//	MYT		马约特
	public static final int LANG_SouthAfrica	= 7177;	//	ZAF	7177	南非
//	public static final int LANG_Zambia	= "ZM";	//	ZMB		赞比亚
//	public static final int LANG_Zimbabwe	= "ZW";	//ZWE		津巴布韦
	
	//国家标识字符串
	public static final String countryAalandIsland = "AX";//	ALA		奥兰群岛
	public static final String countryAzerbaijan = "AZ";//	AZE	2092	阿塞拜疆
	public static final String countryBosniaHerzegovina = "BA";//	BIH	3098	波黑
	public static final String countryBarbados = "BB";//	BRB		巴巴多斯
	public static final String countryBangladesh = "BD";//	BGD		孟加拉
	public static final String countryBelgium = "BE";	//BEL	1059	比利时
	public static final String countryBurkina = "BF";//	BFA		布基纳法索
	public static final String countryBulgaria	= "BG";	//BGR	1026	保加利亚
	public static final String countryBahrain	= "BH";	//	BHR	15361	巴林
	public static final String countryBurundi	= "BI";	//	BDI		布隆迪
	public static final String countryBenin	= "BJ";	//	BEN		贝宁
	public static final String countrySaintBarthelemy	= "BL";	//	BLM		圣巴泰勒米岛
	public static final String countryBermuda	= "BM";	//	BMU		百慕大
	public static final String countryBrunei	= "BN";	//	BRN	2110	文莱
	public static final String countryBolivia	= "BO";	//	BOL	16394	玻利维亚
	public static final String countryCaribbeanNetherlands	= "BQ";	//	BES		荷兰加勒比区
	public static final String countryBrazil	= "BR";	//	BRA	1046	巴西
	public static final String countryBahamas	= "BS";	//	BHS		巴哈马
	public static final String countryBhutan	= "BT";	//	BTN		不丹
	public static final String countryBouvetIsland	= "BV";	//	BVT		布韦岛
	public static final String countryBotswana	= "BW";	//	BWA		博茨瓦纳
	public static final String countryBelarus	= "BY";	//	BLR		白俄罗斯
	public static final String countryBelize	= "BZ";	//	BLZ	10249	伯利兹
	public static final String countryCanada	= "CA";	//	CAN	4105	加拿大
	public static final String countryCocosIslands	= "CC";	//	CCK		科科斯群岛
	public static final String countryDemocraticRepublicoftheCongo	= "CD";	//	COD		刚果（金）
	public static final String countryCentralAfricanRepublic	= "CF";	//	CAF		中非
	public static final String countryRepublicoftheCongo	= "CG";	//	COG		刚果（布）
	public static final String countrySwitzerland	= "CH";	//	CHE	2055	瑞士
	public static final String countryCotedIvoire	= "CI";	//	CIV		科特迪瓦
	public static final String countryCookIslands	= "CK";	//	COK		库克群岛
	public static final String countryChile	= "CL";	//	CHL	13322	智利
	public static final String countryCameroon	= "CM";	//	CMR		喀麦隆
	public static final String countryChina	= "CN";	//	CHN	2052	中国
	public static final String countryColombia	= "CO";	//	COL	9226	哥伦比亚
	public static final String countryCostaRica	= "CR";	//	CRI		哥斯达黎加
	public static final String countryCuba	= "CU";	//	CUB		古巴
	public static final String countryCapeVerde	= "CV";	//	CPV		佛得角
	public static final String countryCuracao	= "CW";	//	CUW		库拉索
	public static final String countryChristmasIsland	= "CX";	//	CXR		圣诞岛
	public static final String countryCyprus	= "CY";	//	CYP		塞浦路斯
	public static final String countryCzechRepublic	= "CZ";	//	CZE		捷克
	public static final String countryGermany	= "DE";	//	DEU	1031	德国
	public static final String countryDjibouti	= "DJ";	//	DJI		吉布提
	public static final String countryDenmark	= "DK";	//	DNK		丹麦
	public static final String countryDominica	= "DM";	//	DMA		多米尼克
	public static final String countryDominicanRepublic	= "DO";	//	DOM	7178	多米尼加
	public static final String countryAlgeria	= "DZ";	//	DZA	5121	阿尔及利亚
	public static final String countryEcuador	= "EC";	//	ECU	12298	厄瓜多尔
	public static final String countryEstonia	= "EE";	//	EST		爱沙尼亚
	public static final String countryEgypt	= "EG";	//	EGY	3073	埃及
	public static final String countryWesternSahara	= "EH";	//	ESH		西撒哈拉
	public static final String countryEritrea	= "ER";	//	ERI		厄立特里亚
	public static final String countrySpain	= "ES";	//	ESP	1034	西班牙
	public static final String countryEthiopia	= "ET";	//	ETH	1061	埃塞俄比亚
	public static final String countryFinland	= "FI";	//	FIN	2077	芬兰
	public static final String countryFiji	= "FJ";	//	FJI		斐济群岛
	public static final String countryFalklandIslands	= "FK";	//	FLK		马尔维纳斯群岛（福克兰）
	public static final String countryFederatedStatesofMicronesia	= "FM";	//	FSM		密克罗尼西亚联邦
	public static final String countryFaroeIslands	= "FO";	//	FRO	1080	法罗群岛
	public static final String countryFrance	= "FR";	//	FRA	1036	法国
	public static final String countryGabon	= "GA";	//	GAB		加蓬
	public static final String countryGreatBritain = "GB";	//	GBR	2057	英国
	public static final String countryGrenada	= "GD";	//	GRD		格林纳达
	public static final String countryGeorgia	= "GE";	//	GEO		格鲁吉亚
	public static final String countryFrenchGuiana	= "GF";	//	GUF		法属圭亚那
	public static final String countryGuernsey	= "GG";	//	GGY		根西岛
	public static final String countryGhana	= "GH";	//	GHA		加纳
	public static final String countryGibraltar	= "GI";	//	GIB		直布罗陀
	public static final String countryGreenland	= "GL";	//	GRL		格陵兰
	public static final String countryGambia	= "GM";	//	GMB		冈比亚
	public static final String countryGuinea	= "GN";	//	GIN		几内亚
	public static final String countryGuadeloupe	= "GP";	//	GLP		瓜德罗普
	public static final String countryEquatorialGuinea	= "GQ";	//	GNQ		赤道几内亚
	public static final String countryGreece	= "GR";	//	GRC	1032	希腊
	public static final String countrySouthGeorgiaandtheSouthSandwichIslands	= "GS";	//	SGS		南乔治亚岛和南桑威奇群岛
	public static final String countryGuatemala	= "GT";	//	GTM	4106	危地马拉
	public static final String countryGuam	= "GU";	//	GUM		关岛
	public static final String countryGuineaBissau	= "GW";	//	GNB		几内亚比绍
	public static final String countryGuyana	= "GY";	//	GUY		圭亚那
	public static final String countryHongKong	= "HK";	//	HKG	3076	香港
	public static final String countryHeardIslandandMcDonaldIslands	= "HM";	//	HMD		赫德岛和麦克唐纳群岛
	public static final String countryHonduras	= "HN";	//	HND	18442	洪都拉斯
	public static final String countryCroatia	= "HR";	//	HRV	1050	克罗地亚
	public static final String countryHaiti	= "HT";	//	HTI		海地
	public static final String countryHungary	= "HU";	//	HUN	1038	匈牙利
	public static final String countryIndonesia	= "ID";	//	IDN	1057	印尼
	public static final String countryIreland	= "IE";	//	IRL	6153	爱尔兰
	public static final String countryIsrael	= "IL";	//	ISR	1037	以色列
	public static final String countryIsleofMan	= "IM";	//	IMN		马恩岛
	public static final String countryIndia	= "IN";	//	IND		印度
	public static final String countryBritishIndianOceanTerritory	= "IO";	//	IOT		英属印度洋领地
	public static final String countryIraq	= "IQ";	//	IRQ	2049	伊拉克
	public static final String countryIran	= "IR";	//	IRN		伊朗
	public static final String countryIceland	= "IS";	//	ISL	1039	冰岛
	public static final String countryItaly	= "IT";	//	ITA	1040	意大利
	public static final String countryJersey	= "JE";	//	JEY		泽西岛
	public static final String countryJamaica	= "JM";	//	JAM	8201	牙买加
	public static final String countryJordan	= "JO";	//	JOR	11265	约旦
	public static final String countryJapan	= "JP";	//	JPN	1041	日本
	public static final String countryKenya	= "KE";	//	KEN	1089	肯尼亚
	public static final String countryKyrgyzstan	= "KG";	//	KGZ		吉尔吉斯斯坦
	public static final String countryCambodia	= "KH";	//	KHM		柬埔寨
	public static final String countryKiribati	= "KI";	//	KIR		基里巴斯
	public static final String countryTheComoros	= "KM";	//	COM		科摩罗
	public static final String countryStKittsNevis	= "KN";	//	KNA		圣基茨和尼维斯
	public static final String countryNorthKorea	= "KP";	//	PRK		朝鲜；
	public static final String countrySouthKorea	= "KR";	//	KOR	1042	韩国；
	public static final String countryKuwait	= "KW";	//	KWT	13313	科威特
	public static final String countryCaymanIslands	= "KY";	//	CYM		开曼群岛
	public static final String countryKazakhstan	= "KZ";	//	KAZ		哈萨克斯坦
	public static final String countryLaos	= "LA";	//	LAO		老挝
	public static final String countryLebanon	= "LB";	//	LBN	12289	黎巴嫩
	public static final String countryStLucia	= "LC";	//	LCA		圣卢西亚
	public static final String countryLiechtenstein	= "LI";	//	LIE	5127	列支敦士登
	public static final String countrySriLanka	= "LK";	//	LKA		斯里兰卡
	public static final String countryLiberia	= "LR";	//	LBR		利比里亚
	public static final String countryLesotho	= "LS";	//	LSO		莱索托
	public static final String countryLithuania	= "LT";	//	LTU	1063	立陶宛
	public static final String countryLuxembourg	= "LU";	//	LUX	4103	卢森堡
	public static final String countryLatvia	= "LV";	//	LVA	1062	拉脱维亚
	public static final String countryLibya	= "LY";	//	LBY	4097	利比亚
	public static final String countryMorocco	= "MA";	//	MAR	6145	摩洛哥
	public static final String countryMonaco	= "MC";	//	MCO		摩纳哥
	public static final String countryMoldova	= "MD";	//	MDA		摩尔多瓦
	public static final String countryMontenegro	= "ME";	//	MNE		黑山
	public static final String countrySaintMartinFrance	= "MF";	//	MAF		法属圣马丁
	public static final String countryMadagascar	= "MG";	//	MDG		马达加斯加
	public static final String countryMarshallIslands	= "MH";	//	MHL		马绍尔群岛
	public static final String countryRepublicofMacedonia	= "MK";	//	MKD	1071	马其顿
	public static final String countryMali	= "ML";	//	MLI		马里
	public static final String countryMyanmarBurma	= "MM";	//	MMR		缅甸
	public static final String countryMongolia	= "MN";	//	MNG		蒙古国；蒙古
	public static final String countryMacao	= "MO";	//	MAC	5124	澳门
	public static final String countryNorthernMarianaIslands	= "MP";	//	MNP		北马里亚纳群岛
	public static final String countryMartinique	= "MQ";	//	MTQ		马提尼克
	public static final String countryMauritania	= "MR";	//	MRT		毛里塔尼亚
	public static final String countryMontserrat	= "MS";	//	MSR		蒙塞拉特岛
	public static final String countryMalta	= "MT";	//	MLT		马耳他
	public static final String countryMauritius	= "MU";	//	MUS		毛里求斯
	public static final String countryMaldives	= "MV";	//	MDV		马尔代夫
	public static final String countryMalawi	= "MW";	//	MWI		马拉维
	public static final String countryMexico	= "MX";	//	MEX	2058	墨西哥
	public static final String countryMalaysia	= "MY";	//	MYS	1086	马来西亚
	public static final String countryMozambique	= "MZ";	//	MOZ		莫桑比克
	public static final String countryNamibia	= "NA";	//	NAM		纳米比亚
	public static final String countryNewCaledonia	= "NC";	//	NCL		新喀里多尼亚
	public static final String countryNiger	= "NE";	//	NER		尼日尔
	public static final String countryNorfolkIsland	= "NF";	//	NFK		诺福克岛
	public static final String countryNigeria	= "NG";	//	NGA		尼日利亚
	public static final String countryNicaragua	= "NI";	//	NIC	19466	尼加拉瓜
	public static final String countryNetherlands	= "NL";	//	NLD	1043	荷兰
	public static final String countryNorway	= "NO";	//	NOR	2068	挪威
	public static final String countryNepal	= "NP";	//	NPL		尼泊尔
	public static final String countryNauru	= "NR";	//	NRU		瑙鲁
	public static final String countryNiue	= "NU";	//	NIU		纽埃
	public static final String countryNewZealand	= "NZ";	//	NZL	5129	新西兰
	public static final String countryOman	= "OM";	//	OMN	8193	阿曼
	public static final String countryPanama	= "PA";	//	PAN	6154	巴拿马
	public static final String countryPeru	= "PE";	//	PER	10250	秘鲁
	public static final String countryFrenchPolynesia	= "PF";	//	PYF		法属波利尼西亚
	public static final String countryPapuaNewGuinea	= "PG";	//	PNG		巴布亚新几内亚
	public static final String countryThePhilippines	= "PH";	//	PHL	13321	菲律宾
	public static final String countryPakistan	= "PK";	//	PAK	1056	巴基斯坦
	public static final String countryPoland	= "PL";	//	POL	1045	波兰
	public static final String countrySaintPierreandMiquelon	= "PM";	//	SPM		圣皮埃尔和密克隆
	public static final String countryPitcairnIslands	= "PN";	//	PCN		皮特凯恩群岛
	public static final String countryPuertoRico	= "PR";	//	PRI	20490	波多黎各
	public static final String countryPalestinianterritories	= "PS";	//	PSE		巴勒斯坦
	public static final String countryPortugal	= "PT";	//	PRT	2070	葡萄牙
	public static final String countryPalau	= "PW";	//	PLW		帕劳
	public static final String countryParaguay	= "PY";	//	PRY	15370	巴拉圭
	public static final String countryQatar	= "QA";	//	QAT	16385	卡塔尔
	public static final String countryRéunion	= "RE";	//	REU		留尼汪
	public static final String countryRomania	= "RO";	//	ROU	1048	罗马尼亚
	public static final String countrySerbia	= "RS";	//	SRB		塞尔维亚
	public static final String countryRussianFederation	= "RU";	//	RUS	1092	俄罗斯
	public static final String countryRwanda	= "RW";	//	RWA		卢旺达
	public static final String countrySaudiArabia	= "SA";	//	SAU	1025	沙特阿拉伯
	public static final String countrySolomonIslands	= "SB";	//	SLB		所罗门群岛
	public static final String countrySeychelles	= "SC";	//	SYC		塞舌尔
	public static final String countrySudan	= "SD";	//	SDN		苏丹
	public static final String countrySweden	= "SE";	//	SWE	1053	瑞典
	public static final String countrySingapore	= "SG";	//	SGP	4100	新加坡
	public static final String countryStHelenaDependencies	= "SH";	//	SHN		圣赫勒拿
	public static final String countrySlovenia	= "SI";	//	SVN		斯洛文尼亚
	public static final String countryTemplateCountrydataSJMSvalbard	= "SJ";	//	SJM		斯瓦尔巴群岛和扬马延岛
	public static final String countrySlovakia	= "SK";	//	SVK	1051	斯洛伐克
	public static final String countrySierraLeone	= "SL";	//	SLE		塞拉利昂
	public static final String countrySanMarino	= "SM";	//	SMR		圣马力诺
	public static final String countrySenegal	= "SN";	//	SEN		塞内加尔
	public static final String countrySomalia	= "SO";	//	SOM		索马里
	public static final String countrySuriname	= "SR";	//	SUR		苏里南
	public static final String countrySouthSudan	= "SS";	//	SSD		南苏丹
	public static final String countrySaoTomePrincipe	= "ST";	//	STP		圣多美和普林西比
	public static final String countryElSalvador	= "SV";	//	SLV	17418	萨尔瓦多
	public static final String countrySintMaarten	= "SX";	//	SXM		荷属圣马丁
	public static final String countrySyria	= "SY";	//	SYR	10241	叙利亚
	public static final String countrySwaziland	= "SZ";	//	SWZ		斯威士兰
	public static final String countryTurksCaicosIslands	= "TC";	//	TCA		特克斯和凯科斯群岛
	public static final String countryChad	= "TD";	//	TCD		乍得
	public static final String countryFrenchSouthernTerritories	= "TF";	//	ATF		法属南部领地
	public static final String countryTogo	= "TG";	//	TGO		多哥
	public static final String countryThailand	= "TH";	//	THA	1054	泰国
	public static final String countryTajikistan	= "TJ";	//	TJK		塔吉克斯坦
	public static final String countryTokelau	= "TK";	//	TKL		托克劳
	public static final String countryTimorLesteEastTimor	= "TL";	//	TLS		东帝汶
	public static final String countryTurkmenistan	= "TM";	//	TKM		土库曼斯坦
	public static final String countryTunisia	= "TN";	//	TUN	7169	突尼斯
	public static final String countryTonga	= "TO";	//	TON		汤加
	public static final String countryTurkey	= "TR";	//	TUR	1055	土耳其
	public static final String countryTrinidadTobago	= "TT";	//	TTO	11273	特立尼达和多巴哥
	public static final String countryTuvalu	= "TV";	//	TUV		图瓦卢
	public static final String countryTaiwan	= "TW";	//	TWN	1028	中国台湾
	public static final String countryTanzania	= "TZ";	//	TZA		坦桑尼亚
	public static final String countryUkraine	= "UA";	//	UKR	1058	乌克兰
	public static final String countryUganda	= "UG";	//	UGA		乌干达
	public static final String countryUnitedStatesMinorOutlyingIslands	= "UM";	//	UMI		美国本土外小岛屿
	public static final String countryAmerica	= "US";	//	USA	1033	美国
	public static final String countryUruguay	= "UY";	//	URY	14346	乌拉圭
	public static final String countryUzbekistan	= "UZ";	//	UZB	2115	乌兹别克斯坦
	public static final String countryVaticanCityTheHolySee	= "VA";	//	VAT		梵蒂冈
	public static final String countryStVincenttheGrenadines	= "VC";	//	VCT		圣文森特和格林纳丁斯
	public static final String countryVenezuela	= "VE";	//	VEN	8202	委内瑞拉
	public static final String countryBritishVirginIslands	= "VG";	//	VGB		英属维尔京群岛
	public static final String countryUnitedStatesVirginIslands	= "VI";	//	VIR		美属维尔京群岛
	public static final String countryVietnam	= "VN";	//	VNM	1066	越南
	public static final String countryVanuatu	= "VU";	//	VUT		瓦努阿图
	public static final String countryWallisandFutuna	= "WF";	//	WLF		瓦利斯和富图纳
	public static final String countrySamoa	= "WS";	//	WSM		萨摩亚
	public static final String countryYemen	= "YE";	//	YEM	9217	也门
	public static final String countryMayotte	= "YT";	//	MYT		马约特
	public static final String countrySouthAfrica	= "ZA";	//	ZAF	7177	南非
	public static final String countryZambia	= "ZM";	//	ZMB		赞比亚
	public static final String countryZimbabwe	= "ZW";	//ZWE		津巴布韦

	
	//VIP过期
	public static final String vipOutOfTime = "vip_out_of_time";
	
	//更新用户信息
    public static final String paymentGetStatus = "payment_get_Status";
    
    //Mopay SDK 返回的状态值
    public static final int MopayStateNone= 0;
    public static final int MopayStateSucc = 1;
    public static final int MopayStateFail = 2;
    public static final int MopayStatePending = 3;
}
