spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: ${mockwebserver.url}/introspect
          introspection-client-id: client
          introspection-client-secret: secret
