// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.7.7 by WSRD Tencent.
// Generated from `SoftUsageInfoInterface.jce'
// **********************************************************************

package com.tencent.onesecurity.usage.qq;

public final class EModelID
{
    private static EModelID[] __values = new EModelID[47];
    private int __value;
    private String __T = new String();
    
    
    public static final int _EMID_Secure_INTO_QQPIMSECURE = 26111;
    public static final EModelID EMID_Secure_INTO_QQPIMSECURE = new EModelID(1076,_EMID_Secure_INTO_QQPIMSECURE,"EMID_Secure_INTO_QQPIMSECURE");
    public static final int _EMID_Secure_Open_desktop_asistant = 27215;
    public static final EModelID EMID_Secure_Open_desktop_asistant = new EModelID(1624,_EMID_Secure_Open_desktop_asistant,"EMID_Secure_Open_desktop_asistant");
    public static final int _EMID_Secure_RUNNING_ONEKEY_DO = 26000;
    public static final EModelID EMID_Secure_RUNNING_ONEKEY_DO = new EModelID(965,_EMID_Secure_RUNNING_ONEKEY_DO,"EMID_Secure_RUNNING_ONEKEY_DO");
    public static final int _EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS = 26272;
    public static final EModelID EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS = new EModelID(1237,_EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS,"EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS");
    public static final int _EMID_Secure_desktop_asistant_into_OS = 27216;
    public static final EModelID EMID_Secure_desktop_asistant_into_OS = new EModelID(1625,_EMID_Secure_desktop_asistant_into_OS,"EMID_Secure_desktop_asistant_into_OS");
    public static final int _EMID_Secure_INTO_MAIN_MENU = 26005;
    public static final EModelID EMID_Secure_INTO_MAIN_MENU = new EModelID(970,_EMID_Secure_INTO_MAIN_MENU,"EMID_Secure_INTO_MAIN_MENU");
    public static final int _EMID_Secure_PROCESSMAIN_ONE_KEY_Boost = 27217;
    public static final EModelID EMID_Secure_PROCESSMAIN_ONE_KEY_Boost = new EModelID(1626,_EMID_Secure_PROCESSMAIN_ONE_KEY_Boost,"EMID_Secure_PROCESSMAIN_ONE_KEY_Boost");
    public static final int _EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN = 26057;
    public static final EModelID EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN = new EModelID(1022,_EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN,"EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN");
    public static final int _EMID_Secure_VirusTabView_Finish_QuickScan = 26198;
    public static final EModelID EMID_Secure_VirusTabView_Finish_QuickScan = new EModelID(1163,_EMID_Secure_VirusTabView_Finish_QuickScan,"EMID_Secure_VirusTabView_Finish_QuickScan");
    public static final int _EMID_Secure_VirusTabView_Finish_FullScan = 26199;
    public static final EModelID EMID_Secure_VirusTabView_Finish_FullScan = new EModelID(1164,_EMID_Secure_VirusTabView_Finish_FullScan,"EMID_Secure_VirusTabView_Finish_FullScan");
    public static final int _EMID_Secure_VirusTabView_Cancel_QuickScan = 26239;
    public static final EModelID EMID_Secure_VirusTabView_Cancel_QuickScan = new EModelID(1204,_EMID_Secure_VirusTabView_Cancel_QuickScan,"EMID_Secure_VirusTabView_Cancel_QuickScan");
    public static final int _EMID_Secure_VirusTabView_Cancel_FullScan = 26240;
    public static final EModelID EMID_Secure_VirusTabView_Cancel_FullScan = new EModelID(1205,_EMID_Secure_VirusTabView_Cancel_FullScan,"EMID_Secure_VirusTabView_Cancel_FullScan");
    public static final int _EMID_Secure_INTO_VIRUS_UPDATE = 26070;
    public static final EModelID EMID_Secure_INTO_VIRUS_UPDATE = new EModelID(1035,_EMID_Secure_INTO_VIRUS_UPDATE,"EMID_Secure_INTO_VIRUS_UPDATE");
    public static final int _EMID_Secure_Notification_VirusLib_Update_Cancel = 26245;
    public static final EModelID EMID_Secure_Notification_VirusLib_Update_Cancel = new EModelID(1210,_EMID_Secure_Notification_VirusLib_Update_Cancel,"EMID_Secure_Notification_VirusLib_Update_Cancel");
    public static final int _EMID_Secure_Outside_VirusTabView_Dont_Kill_Now = 26248;
    public static final EModelID EMID_Secure_Outside_VirusTabView_Dont_Kill_Now = new EModelID(1213,_EMID_Secure_Outside_VirusTabView_Dont_Kill_Now,"EMID_Secure_Outside_VirusTabView_Dont_Kill_Now");
    public static final int _EMID_Secure_Outside_VirusTabView_Kill_Immediately = 26247;
    public static final EModelID EMID_Secure_Outside_VirusTabView_Kill_Immediately = new EModelID(1212,_EMID_Secure_Outside_VirusTabView_Kill_Immediately,"EMID_Secure_Outside_VirusTabView_Kill_Immediately");
    public static final int _EMID_Secure_INTO_US_MAANGER = 26118;
    public static final EModelID EMID_Secure_INTO_US_MAANGER = new EModelID(1083,_EMID_Secure_INTO_US_MAANGER,"EMID_Secure_INTO_US_MAANGER");
    public static final int _EMID_Secure_MV_Create_PASSWORD = 27192;
    public static final EModelID EMID_Secure_MV_Create_PASSWORD = new EModelID(1601,_EMID_Secure_MV_Create_PASSWORD,"EMID_Secure_MV_Create_PASSWORD");
    public static final int _EMID_Secure_MV_Forgot_PASSWORD = 27193;
    public static final EModelID EMID_Secure_MV_Forgot_PASSWORD = new EModelID(1602,_EMID_Secure_MV_Forgot_PASSWORD,"EMID_Secure_MV_Forgot_PASSWORD");
    public static final int _EMID_Secure_MV_INTO_Enter_Correct_PASSWORD = 27194;
    public static final EModelID EMID_Secure_MV_INTO_Enter_Correct_PASSWORD = new EModelID(1603,_EMID_Secure_MV_INTO_Enter_Correct_PASSWORD,"EMID_Secure_MV_INTO_Enter_Correct_PASSWORD");
    public static final int _EMID_Secure_MV_Wrong_PASSWORD = 27195;
    public static final EModelID EMID_Secure_MV_Wrong_PASSWORD = new EModelID(1604,_EMID_Secure_MV_Wrong_PASSWORD,"EMID_Secure_MV_Wrong_PASSWORD");
    public static final int _EMID_Secure_MV_Memo_Enter_PASSWORD = 27196;
    public static final EModelID EMID_Secure_MV_Memo_Enter_PASSWORD = new EModelID(1605,_EMID_Secure_MV_Memo_Enter_PASSWORD,"EMID_Secure_MV_Memo_Enter_PASSWORD");
    public static final int _EMID_Secure_MV_MultiM_Click = 27197;
    public static final EModelID EMID_Secure_MV_MultiM_Click = new EModelID(1606,_EMID_Secure_MV_MultiM_Click,"EMID_Secure_MV_MultiM_Click");
    public static final int _EMID_Secure_MV_MultiM_Enter = 27198;
    public static final EModelID EMID_Secure_MV_MultiM_Enter = new EModelID(1607,_EMID_Secure_MV_MultiM_Enter,"EMID_Secure_MV_MultiM_Enter");
    public static final int _EMID_Secure_INTO_PHONE_UP = 26113;
    public static final EModelID EMID_Secure_INTO_PHONE_UP = new EModelID(1078,_EMID_Secure_INTO_PHONE_UP,"EMID_Secure_INTO_PHONE_UP");
    public static final int _EMID_Secure_MV_PIC_Imp_OK = 27199;
    public static final EModelID EMID_Secure_MV_PIC_Imp_OK = new EModelID(1608,_EMID_Secure_MV_PIC_Imp_OK,"EMID_Secure_MV_PIC_Imp_OK");
    public static final int _EMID_Secure_MV_Video_Imp_OK = 27200;
    public static final EModelID EMID_Secure_MV_Video_Imp_OK = new EModelID(1609,_EMID_Secure_MV_Video_Imp_OK,"EMID_Secure_MV_Video_Imp_OK");
    public static final int _EMID_Secure_MV_Audio_Imp_OK = 27201;
    public static final EModelID EMID_Secure_MV_Audio_Imp_OK = new EModelID(1610,_EMID_Secure_MV_Audio_Imp_OK,"EMID_Secure_MV_Audio_Imp_OK");
    public static final int _EMID_Secure_MV_PIC_Exp_OK = 27202;
    public static final EModelID EMID_Secure_MV_PIC_Exp_OK = new EModelID(1611,_EMID_Secure_MV_PIC_Exp_OK,"EMID_Secure_MV_PIC_Exp_OK");
    public static final int _EMID_Secure_MV_Video_Exp_OK = 27203;
    public static final EModelID EMID_Secure_MV_Video_Exp_OK = new EModelID(1612,_EMID_Secure_MV_Video_Exp_OK,"EMID_Secure_MV_Video_Exp_OK");
    public static final int _EMID_Secure_MV_Audio_Exp_OK = 27204;
    public static final EModelID EMID_Secure_MV_Audio_Exp_OK = new EModelID(1613,_EMID_Secure_MV_Audio_Exp_OK,"EMID_Secure_MV_Audio_Exp_OK");
    public static final int _EMID_Secure_MV_Del_Origin_OK = 27205;
    public static final EModelID EMID_Secure_MV_Del_Origin_OK = new EModelID(1614,_EMID_Secure_MV_Del_Origin_OK,"EMID_Secure_MV_Del_Origin_OK");
    public static final int _EMID_Secure_PRIVATE_PROTECT_password_setting = 26396;
    public static final EModelID EMID_Secure_PRIVATE_PROTECT_password_setting = new EModelID(1361,_EMID_Secure_PRIVATE_PROTECT_password_setting,"EMID_Secure_PRIVATE_PROTECT_password_setting");
    public static final int _EMID_Secure_MV_Setting_Modify = 27206;
    public static final EModelID EMID_Secure_MV_Setting_Modify = new EModelID(1615,_EMID_Secure_MV_Setting_Modify,"EMID_Secure_MV_Setting_Modify");
    public static final int _EMID_Secure_Boost_INTO_VIP = 27207;
    public static final EModelID EMID_Secure_Boost_INTO_VIP = new EModelID(1616,_EMID_Secure_Boost_INTO_VIP,"EMID_Secure_Boost_INTO_VIP");
    public static final int _EMID_Secure_Virus_INTO_VIP = 27208;
    public static final EModelID EMID_Secure_Virus_INTO_VIP = new EModelID(1617,_EMID_Secure_Virus_INTO_VIP,"EMID_Secure_Virus_INTO_VIP");
    public static final int _EMID_Secure_MV_INTO_VIP = 27209;
    public static final EModelID EMID_Secure_MV_INTO_VIP = new EModelID(1618,_EMID_Secure_MV_INTO_VIP,"EMID_Secure_MV_INTO_VIP");
    public static final int _EMID_Secure_VIP_Get_Click = 27210;
    public static final EModelID EMID_Secure_VIP_Get_Click = new EModelID(1619,_EMID_Secure_VIP_Get_Click,"EMID_Secure_VIP_Get_Click");
    public static final int _EMID_Secure_Trial_Get_Click = 27211;
    public static final EModelID EMID_Secure_Trial_Get_Click = new EModelID(1620,_EMID_Secure_Trial_Get_Click,"EMID_Secure_Trial_Get_Click");
    public static final int _EMID_Secure_Trial_Get_SMS_Share = 27212;
    public static final EModelID EMID_Secure_Trial_Get_SMS_Share = new EModelID(1621,_EMID_Secure_Trial_Get_SMS_Share,"EMID_Secure_Trial_Get_SMS_Share");
    public static final int _EMID_Secure_Trial_Obtain = 27213;
    public static final EModelID EMID_Secure_Trial_Obtain = new EModelID(1622,_EMID_Secure_Trial_Obtain,"EMID_Secure_Trial_Obtain");
    public static final int _EMID_Secure_Menu_Setting_SMS_Share = 27214;
    public static final EModelID EMID_Secure_Menu_Setting_SMS_Share = new EModelID(1623,_EMID_Secure_Menu_Setting_SMS_Share,"EMID_Secure_Menu_Setting_SMS_Share");
    public static final int _EMID_Secure_VIP_Pay_Success = 27218;
    public static final EModelID EMID_Secure_VIP_Pay_Success = new EModelID(1627,_EMID_Secure_VIP_Pay_Success,"EMID_Secure_VIP_Pay_Success");
    public static final int _EMID_Secure_MAINVIEW_Into_Menu_Setting = 26250;
    public static final EModelID EMID_Secure_MAINVIEW_Into_Menu_Setting = new EModelID(1215,_EMID_Secure_MAINVIEW_Into_Menu_Setting,"EMID_Secure_MAINVIEW_Into_Menu_Setting");
    //add eddy - 2012-11-23,应danawei需求，增加one sec用户类别三个上报点
    public static final int _EMID_Secure_User_Status_Trial = 27234;
    public static final EModelID EMID_Secure_User_Status_Trial = new EModelID(1674,_EMID_Secure_User_Status_Trial,"EMID_Secure_User_Status_Trial");
    public static final int _EMID_Secure_User_Status_VIP = 27235;
    public static final EModelID EMID_Secure_User_Status_VIP = new EModelID(1675,_EMID_Secure_User_Status_VIP,"EMID_Secure_User_Status_VIP");
    public static final int _EMID_Secure_User_Status_Normal = 27236;
    public static final EModelID EMID_Secure_User_Status_Normal = new EModelID(1676,_EMID_Secure_User_Status_Normal,"EMID_Secure_User_Status_Normal");


    public static EModelID convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static EModelID convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private EModelID(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
