// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class BindEmailResultCode
{
    private static BindEmailResultCode[] __values = new BindEmailResultCode[4];
    private int __value;
    private String __T = new String();

    public static final int _Success = 1;
    public static final BindEmailResultCode Success = new BindEmailResultCode(0,_Success,"Success");
    public static final int _InvalidParameter = -1;
    public static final BindEmailResultCode InvalidParameter = new BindEmailResultCode(1,_InvalidParameter,"InvalidParameter");
    public static final int _Fail = -2;
    public static final BindEmailResultCode Fail = new BindEmailResultCode(2,_Fail,"Fail");
    public static final int _InUse = -3;
    public static final BindEmailResultCode InUse = new BindEmailResultCode(3,_InUse,"InUse");

    public static BindEmailResultCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static BindEmailResultCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private BindEmailResultCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
