// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class BindEmailRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = -6776567704944698406L;
	public String className()
    {
        return "QQPIM.BindEmailRequest";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.BindEmailRequest";
    }

    public String email = "";

    public String imei = "";

    public int languageFlag = 0;

    public String getEmail()
    {
        return email;
    }

    public void  setEmail(String email)
    {
        this.email = email;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public int getLanguageFlag()
    {
        return languageFlag;
    }

    public void  setLanguageFlag(int languageFlag)
    {
        this.languageFlag = languageFlag;
    }

    public BindEmailRequest()
    {
        setEmail(email);
        setImei(imei);
        setLanguageFlag(languageFlag);
    }

    public BindEmailRequest(String email, String imei, int languageFlag)
    {
        setEmail(email);
        setImei(imei);
        setLanguageFlag(languageFlag);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        BindEmailRequest t = (BindEmailRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(email, t.email) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(languageFlag, t.languageFlag) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(email, 0);
        _os.write(imei, 1);
        _os.write(languageFlag, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setEmail( _is.readString(0, true));

        setImei( _is.readString(1, true));

        setLanguageFlag((int) _is.read(languageFlag, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(email, "email");
        _ds.display(imei, "imei");
        _ds.display(languageFlag, "languageFlag");
    }

}

