// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class BsharkConfig extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = 6417667322824790599L;

	public String className()
    {
        return "QQPIM.BsharkConfig";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.BsharkConfig";
    }

    public String sms = "";

    public String to = "";

    public String tips = "";

    public String getSms()
    {
        return sms;
    }

    public void  setSms(String sms)
    {
        this.sms = sms;
    }

    public String getTo()
    {
        return to;
    }

    public void  setTo(String to)
    {
        this.to = to;
    }

    public String getTips()
    {
        return tips;
    }

    public void  setTips(String tips)
    {
        this.tips = tips;
    }

    public BsharkConfig()
    {
        setSms(sms);
        setTo(to);
        setTips(tips);
    }

    public BsharkConfig(String sms, String to, String tips)
    {
        setSms(sms);
        setTo(to);
        setTips(tips);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        BsharkConfig t = (BsharkConfig) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sms, t.sms) && 
            com.qq.taf.jce.JceUtil.equals(to, t.to) && 
            com.qq.taf.jce.JceUtil.equals(tips, t.tips) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sms, 0);
        _os.write(to, 1);
        _os.write(tips, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setSms( _is.readString(0, true));

        setTo( _is.readString(1, true));

        setTips( _is.readString(2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sms, "sms");
        _ds.display(to, "to");
        _ds.display(tips, "tips");
    }

}

