// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class GooglePayResultRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = 9102000440803669355L;

	public String className()
    {
        return "QQPIM.GooglePayResultRequest";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.GooglePayResultRequest";
    }

    public long time = 0;

    public String imei = "";

    public String deviceToken = "";

    public int status = 0;

    public long startTime = 0;

    public long endTime = 0;

    public int month = 0;

    public long getTime()
    {
        return time;
    }

    public void  setTime(long time)
    {
        this.time = time;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getDeviceToken()
    {
        return deviceToken;
    }

    public void  setDeviceToken(String deviceToken)
    {
        this.deviceToken = deviceToken;
    }

    public int getStatus()
    {
        return status;
    }

    public void  setStatus(int status)
    {
        this.status = status;
    }

    public long getStartTime()
    {
        return startTime;
    }

    public void  setStartTime(long startTime)
    {
        this.startTime = startTime;
    }

    public long getEndTime()
    {
        return endTime;
    }

    public void  setEndTime(long endTime)
    {
        this.endTime = endTime;
    }

    public int getMonth()
    {
        return month;
    }

    public void  setMonth(int month)
    {
        this.month = month;
    }

    public GooglePayResultRequest()
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setStatus(status);
        setStartTime(startTime);
        setEndTime(endTime);
        setMonth(month);
    }

    public GooglePayResultRequest(long time, String imei, String deviceToken, int status, long startTime, long endTime, int month)
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setStatus(status);
        setStartTime(startTime);
        setEndTime(endTime);
        setMonth(month);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GooglePayResultRequest t = (GooglePayResultRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(time, t.time) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(deviceToken, t.deviceToken) && 
            com.qq.taf.jce.JceUtil.equals(status, t.status) && 
            com.qq.taf.jce.JceUtil.equals(startTime, t.startTime) && 
            com.qq.taf.jce.JceUtil.equals(endTime, t.endTime) && 
            com.qq.taf.jce.JceUtil.equals(month, t.month) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(time, 0);
        _os.write(imei, 1);
        _os.write(deviceToken, 2);
        _os.write(status, 3);
        _os.write(startTime, 4);
        _os.write(endTime, 5);
        _os.write(month, 6);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setTime((long) _is.read(time, 0, true));

        setImei( _is.readString(1, true));

        setDeviceToken( _is.readString(2, true));

        setStatus((int) _is.read(status, 3, true));

        setStartTime((long) _is.read(startTime, 4, true));

        setEndTime((long) _is.read(endTime, 5, true));

        setMonth((int) _is.read(month, 6, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(time, "time");
        _ds.display(imei, "imei");
        _ds.display(deviceToken, "deviceToken");
        _ds.display(status, "status");
        _ds.display(startTime, "startTime");
        _ds.display(endTime, "endTime");
        _ds.display(month, "month");
    }

}

