// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class PayResult extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = -337264797598782015L;

	public String className()
    {
        return "QQPIM.PayResult";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.PayResult";
    }

    public long time = 0;

    public String imei = "";

    public String deviceToken = "";

    public int resultCode = 0;

    public String resultTips = "";

    public PayStatus payStatus = null;

    public long getTime()
    {
        return time;
    }

    public void  setTime(long time)
    {
        this.time = time;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getDeviceToken()
    {
        return deviceToken;
    }

    public void  setDeviceToken(String deviceToken)
    {
        this.deviceToken = deviceToken;
    }

    public int getResultCode()
    {
        return resultCode;
    }

    public void  setResultCode(int resultCode)
    {
        this.resultCode = resultCode;
    }

    public String getResultTips()
    {
        return resultTips;
    }

    public void  setResultTips(String resultTips)
    {
        this.resultTips = resultTips;
    }

    public PayStatus getPayStatus()
    {
        return payStatus;
    }

    public void  setPayStatus(PayStatus payStatus)
    {
        this.payStatus = payStatus;
    }

    public PayResult()
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setResultCode(resultCode);
        setResultTips(resultTips);
        setPayStatus(payStatus);
    }

    public PayResult(long time, String imei, String deviceToken, int resultCode, String resultTips, PayStatus payStatus)
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setResultCode(resultCode);
        setResultTips(resultTips);
        setPayStatus(payStatus);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PayResult t = (PayResult) o;
        return (
            com.qq.taf.jce.JceUtil.equals(time, t.time) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(deviceToken, t.deviceToken) && 
            com.qq.taf.jce.JceUtil.equals(resultCode, t.resultCode) && 
            com.qq.taf.jce.JceUtil.equals(resultTips, t.resultTips) && 
            com.qq.taf.jce.JceUtil.equals(payStatus, t.payStatus) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(time, 0);
        _os.write(imei, 1);
        _os.write(deviceToken, 2);
        _os.write(resultCode, 3);
        _os.write(resultTips, 4);
        if (null != payStatus)
        {
            _os.write(payStatus, 5);
        }
    }

    static int cache_resultCode;
    static PayStatus cache_payStatus;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setTime((long) _is.read(time, 0, true));

        setImei( _is.readString(1, true));

        setDeviceToken( _is.readString(2, true));

        setResultCode((int) _is.read(resultCode, 3, true));

        setResultTips( _is.readString(4, true));

        if(null == cache_payStatus)
        {
            cache_payStatus = new PayStatus();
        }
        setPayStatus((PayStatus) _is.read(cache_payStatus, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(time, "time");
        _ds.display(imei, "imei");
        _ds.display(deviceToken, "deviceToken");
        _ds.display(resultCode, "resultCode");
        _ds.display(resultTips, "resultTips");
        _ds.display(payStatus, "payStatus");
    }

}

