// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class PayRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = -5886188698154448210L;

	public String className()
    {
        return "QQPIM.PayRequest";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.PayRequest";
    }

    public long time = 0;

    public String imei = "";

    public String deviceToken = "";

    public int appId = 0;

    public String lc = "";

    public int channelId = 0;

    public int languageFlag = 0;

    public String phoneNumber = "";

    public String imsi = "";

    public String country = "";

    public int clientPayStatus = 0;

    public String clientPayErrorMsg = "";
    public int promotionId = 0;

    public long getTime()
    {
        return time;
    }

    public void  setTime(long time)
    {
        this.time = time;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getDeviceToken()
    {
        return deviceToken;
    }

    public void  setDeviceToken(String deviceToken)
    {
        this.deviceToken = deviceToken;
    }

    public int getAppId()
    {
        return appId;
    }

    public void  setAppId(int appId)
    {
        this.appId = appId;
    }

    public String getLc()
    {
        return lc;
    }

    public void  setLc(String lc)
    {
        this.lc = lc;
    }

    public int getChannelId()
    {
        return channelId;
    }

    public void  setChannelId(int channelId)
    {
        this.channelId = channelId;
    }

    public int getLanguageFlag()
    {
        return languageFlag;
    }

    public void  setLanguageFlag(int languageFlag)
    {
        this.languageFlag = languageFlag;
    }

    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    public void  setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    public String getImsi()
    {
        return imsi;
    }

    public void  setImsi(String imsi)
    {
        this.imsi = imsi;
    }

    public String getCountry()
    {
        return country;
    }

    public void  setCountry(String country)
    {
        this.country = country;
    }

    public int getClientPayStatus()
    {
        return clientPayStatus;
    }

    public void  setClientPayStatus(int clientPayStatus)
    {
        this.clientPayStatus = clientPayStatus;
    }

    public String getClientPayErrorMsg()
    {
        return clientPayErrorMsg;
    }

    public void  setClientPayErrorMsg(String clientPayErrorMsg)
    {
        this.clientPayErrorMsg = clientPayErrorMsg;
    }

    public int getPromotionId()
    {
        return promotionId;
    }
    public void  setPromotionId(int promotionId)
    {
        this.promotionId = promotionId;
    }
    public PayRequest()
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setLanguageFlag(languageFlag);
        setPhoneNumber(phoneNumber);
        setImsi(imsi);
        setCountry(country);
        setClientPayStatus(clientPayStatus);
        setClientPayErrorMsg(clientPayErrorMsg);
        setPromotionId(promotionId);
    }

    public PayRequest(long time, String imei, String deviceToken, int appId, String lc, int channelId, int languageFlag, String phoneNumber, String imsi, String country, int clientPayStatus, String clientPayErrorMsg, int promotionId)
    {
        setTime(time);
        setImei(imei);
        setDeviceToken(deviceToken);
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setLanguageFlag(languageFlag);
        setPhoneNumber(phoneNumber);
        setImsi(imsi);
        setCountry(country);
        setClientPayStatus(clientPayStatus);
        setClientPayErrorMsg(clientPayErrorMsg);
        setPromotionId(promotionId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PayRequest t = (PayRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(time, t.time) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(deviceToken, t.deviceToken) && 
            com.qq.taf.jce.JceUtil.equals(appId, t.appId) && 
            com.qq.taf.jce.JceUtil.equals(lc, t.lc) && 
            com.qq.taf.jce.JceUtil.equals(channelId, t.channelId) && 
            com.qq.taf.jce.JceUtil.equals(languageFlag, t.languageFlag) && 
            com.qq.taf.jce.JceUtil.equals(phoneNumber, t.phoneNumber) && 
            com.qq.taf.jce.JceUtil.equals(imsi, t.imsi) && 
            com.qq.taf.jce.JceUtil.equals(country, t.country) && 
            com.qq.taf.jce.JceUtil.equals(clientPayStatus, t.clientPayStatus) && 
            com.qq.taf.jce.JceUtil.equals(clientPayErrorMsg, t.clientPayErrorMsg) && 
            com.qq.taf.jce.JceUtil.equals(promotionId, t.promotionId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(time, 0);
        _os.write(imei, 1);
        _os.write(deviceToken, 2);
        _os.write(appId, 3);
        if (null != lc)
        {
            _os.write(lc, 4);
        }
        _os.write(channelId, 5);
        _os.write(languageFlag, 6);
        if (null != phoneNumber)
        {
            _os.write(phoneNumber, 7);
        }
        if (null != imsi)
        {
            _os.write(imsi, 8);
        }
        if (null != country)
        {
            _os.write(country, 9);
        }
        _os.write(clientPayStatus, 10);
        if (null != clientPayErrorMsg)
        {
            _os.write(clientPayErrorMsg, 11);
        }
        _os.write(promotionId, 12);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setTime((long) _is.read(time, 0, true));

        setImei( _is.readString(1, true));

        setDeviceToken( _is.readString(2, true));

        setAppId((int) _is.read(appId, 3, false));

        setLc( _is.readString(4, false));

        setChannelId((int) _is.read(channelId, 5, false));

        setLanguageFlag((int) _is.read(languageFlag, 6, false));

        setPhoneNumber( _is.readString(7, false));

        setImsi( _is.readString(8, false));

        setCountry( _is.readString(9, false));

        setClientPayStatus((int) _is.read(clientPayStatus, 10, false));

        setClientPayErrorMsg( _is.readString(11, false));
        setPromotionId((int) _is.read(promotionId, 12, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(time, "time");
        _ds.display(imei, "imei");
        _ds.display(deviceToken, "deviceToken");
        _ds.display(appId, "appId");
        _ds.display(lc, "lc");
        _ds.display(channelId, "channelId");
        _ds.display(languageFlag, "languageFlag");
        _ds.display(phoneNumber, "phoneNumber");
        _ds.display(imsi, "imsi");
        _ds.display(country, "country");
        _ds.display(clientPayStatus, "clientPayStatus");
        _ds.display(clientPayErrorMsg, "clientPayErrorMsg");
        _ds.display(promotionId, "promotionId");
    }

}

