// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class PayRequestHolder
{
    public PayRequestHolder()
    {
    }
    public PayRequestHolder(PayRequest value)
    {
        this.value = value;
    }

    public PayRequest value;
}
