// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class PayStatus extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = 6965145758328328558L;

	public String className()
    {
        return "QQPIM.PayStatus";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.PayStatus";
    }

    public long startTime = 0;

    public long endTime = 0;

    public long surplusTime = 0;

    public int status = 0;

    public int type = 0;

    public String email = "";
    public long currentTime = 0;

    public long getStartTime()
    {
        return startTime;
    }

    public void  setStartTime(long startTime)
    {
        this.startTime = startTime;
    }

    public long getEndTime()
    {
        return endTime;
    }

    public void  setEndTime(long endTime)
    {
        this.endTime = endTime;
    }

    public long getSurplusTime()
    {
        return surplusTime;
    }

    public void  setSurplusTime(long surplusTime)
    {
        this.surplusTime = surplusTime;
    }

    public int getStatus()
    {
        return status;
    }

    public void  setStatus(int status)
    {
        this.status = status;
    }

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public String getEmail()
    {
        return email;
    }

    public void  setEmail(String email)
    {
        this.email = email;
    }

    public long getCurrentTime()
    {
        return currentTime;
    }
    public void  setCurrentTime(long currentTime)
    {
        this.currentTime = currentTime;
    }
    public PayStatus()
    {
        setStartTime(startTime);
        setEndTime(endTime);
        setSurplusTime(surplusTime);
        setStatus(status);
        setType(type);
        setEmail(email);
        setCurrentTime(currentTime);
    }

    public PayStatus(long startTime, long endTime, long surplusTime, int status, int type, String email, long currentTime)
    {
        setStartTime(startTime);
        setEndTime(endTime);
        setSurplusTime(surplusTime);
        setStatus(status);
        setType(type);
        setEmail(email);
        setCurrentTime(currentTime);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PayStatus t = (PayStatus) o;
        return (
            com.qq.taf.jce.JceUtil.equals(startTime, t.startTime) && 
            com.qq.taf.jce.JceUtil.equals(endTime, t.endTime) && 
            com.qq.taf.jce.JceUtil.equals(surplusTime, t.surplusTime) && 
            com.qq.taf.jce.JceUtil.equals(status, t.status) && 
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(email, t.email) && 
            com.qq.taf.jce.JceUtil.equals(currentTime, t.currentTime) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(startTime, 0);
        _os.write(endTime, 1);
        _os.write(surplusTime, 2);
        _os.write(status, 3);
        _os.write(type, 4);
        _os.write(email, 5);
        _os.write(currentTime, 6);
    }

    static int cache_status;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setStartTime((long) _is.read(startTime, 0, true));

        setEndTime((long) _is.read(endTime, 1, true));

        setSurplusTime((long) _is.read(surplusTime, 2, true));

        setStatus((int) _is.read(status, 3, true));

        setType((int) _is.read(type, 4, true));

        setEmail( _is.readString(5, true));

        setCurrentTime((long) _is.read(currentTime, 6, false));
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(startTime, "startTime");
        _ds.display(endTime, "endTime");
        _ds.display(surplusTime, "surplusTime");
        _ds.display(status, "status");
        _ds.display(type, "type");
        _ds.display(email, "email");
        _ds.display(currentTime, "currentTime");
    }

}

