// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class ResultCode
{
    private static ResultCode[] __values = new ResultCode[6];
    private int __value;
    private String __T = new String();

    public static final int _Processing = 0;
    public static final ResultCode Processing = new ResultCode(0,_Processing,"Processing");
    public static final int _Success = 1;
    public static final ResultCode Success = new ResultCode(1,_Success,"Success");
    public static final int _InvalidParameter = -1;
    public static final ResultCode InvalidParameter = new ResultCode(2,_InvalidParameter,"InvalidParameter");
    public static final int _Fail = -2;
    public static final ResultCode Fail = new ResultCode(3,_Fail,"Fail");
    public static final int _Cancel = -3;
    public static final ResultCode Cancel = new ResultCode(4,_Cancel,"Cancel");
    public static final int _Unknown = -4;
    public static final ResultCode Unknown = new ResultCode(5,_Unknown,"Unknown");

    public static ResultCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ResultCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ResultCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
