// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class StatusCode
{
    private static StatusCode[] __values = new StatusCode[6];
    private int __value;
    private String __T = new String();

    public static final int _Off = 0;
    public static final StatusCode Off = new StatusCode(0,_Off,"Off");
    public static final int _On = 1;
    public static final StatusCode On = new StatusCode(1,_On,"On");
    public static final int _Expire = 2;
    public static final StatusCode Expire = new StatusCode(2,_Expire,"Expire");
    public static final int _Trial = 3;
    public static final StatusCode Trial = new StatusCode(3,_Trial,"Trial");
    public static final int _Exception = 4;
    public static final StatusCode Exception = new StatusCode(4,_Exception,"Exception");
    public static final int _Preset = 5;
    public static final StatusCode Preset = new StatusCode(5,_Preset,"Preset");

    public static StatusCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static StatusCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private StatusCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
