// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class VerifyEmailRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = 64619102053972707L;

	public String className()
    {
        return "QQPIM.VerifyEmailRequest";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.VerifyEmailRequest";
    }

    public String verifyCode = "";

    public String imei = "";

    public boolean autoAdd = true;

    public String getVerifyCode()
    {
        return verifyCode;
    }

    public void  setVerifyCode(String verifyCode)
    {
        this.verifyCode = verifyCode;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public boolean getAutoAdd()
    {
        return autoAdd;
    }

    public void  setAutoAdd(boolean autoAdd)
    {
        this.autoAdd = autoAdd;
    }

    public VerifyEmailRequest()
    {
        setVerifyCode(verifyCode);
        setImei(imei);
        setAutoAdd(autoAdd);
    }

    public VerifyEmailRequest(String verifyCode, String imei, boolean autoAdd)
    {
        setVerifyCode(verifyCode);
        setImei(imei);
        setAutoAdd(autoAdd);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        VerifyEmailRequest t = (VerifyEmailRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(verifyCode, t.verifyCode) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(autoAdd, t.autoAdd) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(verifyCode, 0);
        _os.write(imei, 1);
        _os.write(autoAdd, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setVerifyCode( _is.readString(0, true));

        setImei( _is.readString(1, true));

        setAutoAdd((boolean) _is.read(autoAdd, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(verifyCode, "verifyCode");
        _ds.display(imei, "imei");
        _ds.display(autoAdd, "autoAdd");
    }

}

