// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class VIPTrialResultRequestHolder
{
    public VIPTrialResultRequestHolder()
    {
    }
    public VIPTrialResultRequestHolder(VIPTrialResultRequest value)
    {
        this.value = value;
    }

    public VIPTrialResultRequest value;
}
