// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `Pay.jce'
// **********************************************************************

package com.tencent.onesecurity.service.QQPIM;

public final class VIPTrialResultRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
	private static final long serialVersionUID = 8038527926525008930L;

	public String className()
    {
        return "QQPIM.VIPTrialResultRequest";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.service.QQPIM.VIPTrialResultRequest";
    }

    public String imei = "";

    public int appId = 0;

    public String lc = "";

    public int channelId = 0;

    public String phoneNumber = "";

    public String imsi = "";

    public String country = "";

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public int getAppId()
    {
        return appId;
    }

    public void  setAppId(int appId)
    {
        this.appId = appId;
    }

    public String getLc()
    {
        return lc;
    }

    public void  setLc(String lc)
    {
        this.lc = lc;
    }

    public int getChannelId()
    {
        return channelId;
    }

    public void  setChannelId(int channelId)
    {
        this.channelId = channelId;
    }

    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    public void  setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    public String getImsi()
    {
        return imsi;
    }

    public void  setImsi(String imsi)
    {
        this.imsi = imsi;
    }

    public String getCountry()
    {
        return country;
    }

    public void  setCountry(String country)
    {
        this.country = country;
    }

    public VIPTrialResultRequest()
    {
        setImei(imei);
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setPhoneNumber(phoneNumber);
        setImsi(imsi);
        setCountry(country);
    }

    public VIPTrialResultRequest(String imei, int appId, String lc, int channelId, String phoneNumber, String imsi, String country)
    {
        setImei(imei);
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setPhoneNumber(phoneNumber);
        setImsi(imsi);
        setCountry(country);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        VIPTrialResultRequest t = (VIPTrialResultRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(appId, t.appId) && 
            com.qq.taf.jce.JceUtil.equals(lc, t.lc) && 
            com.qq.taf.jce.JceUtil.equals(channelId, t.channelId) && 
            com.qq.taf.jce.JceUtil.equals(phoneNumber, t.phoneNumber) && 
            com.qq.taf.jce.JceUtil.equals(imsi, t.imsi) && 
            com.qq.taf.jce.JceUtil.equals(country, t.country) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(imei, 0);
        _os.write(appId, 1);
        if (null != lc)
        {
            _os.write(lc, 2);
        }
        _os.write(channelId, 3);
        if (null != phoneNumber)
        {
            _os.write(phoneNumber, 4);
        }
        if (null != imsi)
        {
            _os.write(imsi, 5);
        }
        if (null != country)
        {
            _os.write(country, 6);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setImei( _is.readString(0, true));

        setAppId((int) _is.read(appId, 1, false));

        setLc( _is.readString(2, false));

        setChannelId((int) _is.read(channelId, 3, false));

        setPhoneNumber( _is.readString(4, false));

        setImsi( _is.readString(5, false));

        setCountry( _is.readString(6, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(imei, "imei");
        _ds.display(appId, "appId");
        _ds.display(lc, "lc");
        _ds.display(channelId, "channelId");
        _ds.display(phoneNumber, "phoneNumber");
        _ds.display(imsi, "imsi");
        _ds.display(country, "country");
    }

}

