// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(11).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class AppInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String className()
    {
        return "AppInfo";
    }

    public String fullClassName()
    {
        return "AppInfo";
    }

    public String appId = "";

    public String appName = "";

    public int appReportType = 0;

    public VirusInfo virusInfo = null;

    public String getAppId()
    {
        return appId;
    }

    public void  setAppId(String appId)
    {
        this.appId = appId;
    }

    public String getAppName()
    {
        return appName;
    }

    public void  setAppName(String appName)
    {
        this.appName = appName;
    }

    public int getAppReportType()
    {
        return appReportType;
    }

    public void  setAppReportType(int appReportType)
    {
        this.appReportType = appReportType;
    }

    public VirusInfo getVirusInfo()
    {
        return virusInfo;
    }

    public void  setVirusInfo(VirusInfo virusInfo)
    {
        this.virusInfo = virusInfo;
    }

    public AppInfo()
    {
        setAppId(appId);
        setAppName(appName);
        setAppReportType(appReportType);
        setVirusInfo(virusInfo);
    }

    public AppInfo(String appId, String appName, int appReportType, VirusInfo virusInfo)
    {
        setAppId(appId);
        setAppName(appName);
        setAppReportType(appReportType);
        setVirusInfo(virusInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInfo t = (AppInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(appId, t.appId) && 
            com.qq.taf.jce.JceUtil.equals(appName, t.appName) && 
            com.qq.taf.jce.JceUtil.equals(appReportType, t.appReportType) && 
            com.qq.taf.jce.JceUtil.equals(virusInfo, t.virusInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(appId, 0);
        _os.write(appName, 1);
        _os.write(appReportType, 2);
        if (null != virusInfo)
        {
            _os.write(virusInfo, 3);
        }
    }

    static int cache_appReportType;
    static VirusInfo cache_virusInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setAppId( _is.readString(0, true));

        setAppName( _is.readString(1, true));

        setAppReportType((int) _is.read(appReportType, 2, true));

        if(null == cache_virusInfo)
        {
            cache_virusInfo = new VirusInfo();
        }
        setVirusInfo((VirusInfo) _is.read(cache_virusInfo, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(appId, "appId");
        _ds.display(appName, "appName");
        _ds.display(appReportType, "appReportType");
        _ds.display(virusInfo, "virusInfo");
    }

}

