// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class DATA_REPORT_TYPE
{
    private static DATA_REPORT_TYPE[] __values = new DATA_REPORT_TYPE[45];
    private int __value;
    private String __T = new String();

    public static final int _DR_UserInfoType = 0;
    public static final DATA_REPORT_TYPE DR_UserInfoType = new DATA_REPORT_TYPE(0,_DR_UserInfoType,"DR_UserInfoType");
    public static final int _EMID_Secure_INTO_QQPIMSECURE = 1;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_QQPIMSECURE = new DATA_REPORT_TYPE(1,_EMID_Secure_INTO_QQPIMSECURE,"EMID_Secure_INTO_QQPIMSECURE");
    public static final int _EMID_Secure_Open_desktop_asistant = 2;
    public static final DATA_REPORT_TYPE EMID_Secure_Open_desktop_asistant = new DATA_REPORT_TYPE(2,_EMID_Secure_Open_desktop_asistant,"EMID_Secure_Open_desktop_asistant");
    
    
    public static final int _EMID_Secure_RUNNING_ONEKEY_DO = 3;
    public static final DATA_REPORT_TYPE EMID_Secure_RUNNING_ONEKEY_DO = new DATA_REPORT_TYPE(3,_EMID_Secure_RUNNING_ONEKEY_DO,"EMID_Secure_RUNNING_ONEKEY_DO");
    
    public static final int _EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS = 4;
    public static final DATA_REPORT_TYPE EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS = new DATA_REPORT_TYPE(4,_EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS,"EMID_Secure_ASSISTANT_ROCKET_LAUNCH_SUCCESS");
    
    public static final int _EMID_Secure_desktop_asistant_into_OS = 5;
    public static final DATA_REPORT_TYPE EMID_Secure_desktop_asistant_into_OS = new DATA_REPORT_TYPE(5,_EMID_Secure_desktop_asistant_into_OS,"EMID_Secure_desktop_asistant_into_OS");
    
    public static final int _EMID_Secure_INTO_MAIN_MENU = 6;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_MAIN_MENU = new DATA_REPORT_TYPE(6,_EMID_Secure_INTO_MAIN_MENU,"EMID_Secure_INTO_MAIN_MENU");
    
    public static final int _EMID_Secure_INTO_PHONE_UP = 7;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_PHONE_UP = new DATA_REPORT_TYPE(7,_EMID_Secure_INTO_PHONE_UP,"EMID_Secure_INTO_PHONE_UP");
    
    public static final int _EMID_Secure_PROCESSMAIN_ONE_KEY_Boost = 8;
    public static final DATA_REPORT_TYPE EMID_Secure_PROCESSMAIN_ONE_KEY_Boost = new DATA_REPORT_TYPE(8,_EMID_Secure_PROCESSMAIN_ONE_KEY_Boost,"EMID_Secure_PROCESSMAIN_ONE_KEY_Boost");
    
    public static final int _EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN = 9;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN = new DATA_REPORT_TYPE(9,_EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN,"EMID_Secure_INTO_MIANVIEW_VIRUS_SCAN");
    
    
    public static final int _EMID_Secure_VirusTabView_Finish_QuickScan = 10;
    public static final DATA_REPORT_TYPE EMID_Secure_VirusTabView_Finish_QuickScan = new DATA_REPORT_TYPE(10,_EMID_Secure_VirusTabView_Finish_QuickScan,"EMID_Secure_VirusTabView_Finish_QuickScan");
    
    public static final int _EMID_Secure_VirusTabView_Finish_FullScan = 11;
    public static final DATA_REPORT_TYPE EMID_Secure_VirusTabView_Finish_FullScan = new DATA_REPORT_TYPE(11,_EMID_Secure_VirusTabView_Finish_FullScan,"EMID_Secure_VirusTabView_Finish_FullScan");
    
    public static final int _EMID_Secure_VirusTabView_Cancel_QuickScan = 12;
    public static final DATA_REPORT_TYPE EMID_Secure_VirusTabView_Cancel_QuickScan = new DATA_REPORT_TYPE(12,_EMID_Secure_VirusTabView_Cancel_QuickScan,"EMID_Secure_VirusTabView_Cancel_QuickScan");
    
    public static final int _EMID_Secure_VirusTabView_Cancel_FullScan = 13;
    public static final DATA_REPORT_TYPE EMID_Secure_VirusTabView_Cancel_FullScan = new DATA_REPORT_TYPE(13,_EMID_Secure_VirusTabView_Cancel_FullScan,"EMID_Secure_VirusTabView_Cancel_FullScan");
    
    public static final int _EMID_Secure_INTO_VIRUS_UPDATE = 14;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_VIRUS_UPDATE = new DATA_REPORT_TYPE(14,_EMID_Secure_INTO_VIRUS_UPDATE,"EMID_Secure_INTO_VIRUS_UPDATE");
    
    public static final int _EMID_Secure_Notification_VirusLib_Update_Cancel = 15;
    public static final DATA_REPORT_TYPE EMID_Secure_Notification_VirusLib_Update_Cancel = new DATA_REPORT_TYPE(15,_EMID_Secure_Notification_VirusLib_Update_Cancel,"EMID_Secure_Notification_VirusLib_Update_Cancel");
    
    public static final int _EMID_Secure_Outside_VirusTabView_Dont_Kill_Now = 16;
    public static final DATA_REPORT_TYPE EMID_Secure_Outside_VirusTabView_Dont_Kill_Now = new DATA_REPORT_TYPE(16,_EMID_Secure_Outside_VirusTabView_Dont_Kill_Now,"EMID_Secure_Outside_VirusTabView_Dont_Kill_Now");
    
    public static final int _EMID_Secure_Outside_VirusTabView_Kill_Immediately = 17;
    public static final DATA_REPORT_TYPE EMID_Secure_Outside_VirusTabView_Kill_Immediately = new DATA_REPORT_TYPE(17,_EMID_Secure_Outside_VirusTabView_Kill_Immediately,"EMID_Secure_Outside_VirusTabView_Kill_Immediately");
    
    public static final int _EMID_Secure_INTO_US_MAANGER = 18;
    public static final DATA_REPORT_TYPE EMID_Secure_INTO_US_MAANGER = new DATA_REPORT_TYPE(18,_EMID_Secure_INTO_US_MAANGER,"EMID_Secure_INTO_US_MAANGER");
    
    public static final int _EMID_Secure_MV_Create_PASSWORD = 19;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Create_PASSWORD = new DATA_REPORT_TYPE(19,_EMID_Secure_MV_Create_PASSWORD,"EMID_Secure_MV_Create_PASSWORD");
    
    public static final int _EMID_Secure_MV_Forgot_PASSWORD = 20;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Forgot_PASSWORD = new DATA_REPORT_TYPE(20,_EMID_Secure_MV_Forgot_PASSWORD,"EMID_Secure_MV_Forgot_PASSWORD");
    
    public static final int _EMID_Secure_MV_INTO_Enter_Correct_PASSWORD = 21;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_INTO_Enter_Correct_PASSWORD = new DATA_REPORT_TYPE(21,_EMID_Secure_MV_INTO_Enter_Correct_PASSWORD,"EMID_Secure_MV_INTO_Enter_Correct_PASSWORD");
    
    public static final int _EMID_Secure_MV_Wrong_PASSWORD = 22;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Wrong_PASSWORD = new DATA_REPORT_TYPE(22,_EMID_Secure_MV_Wrong_PASSWORD,"EMID_Secure_MV_Wrong_PASSWORD");
    
    public static final int _EMID_Secure_MV_Memo_Enter_PASSWORD = 23;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Memo_Enter_PASSWORD = new DATA_REPORT_TYPE(23,_EMID_Secure_MV_Memo_Enter_PASSWORD,"EMID_Secure_MV_Memo_Enter_PASSWORD");
    
    public static final int _EMID_Secure_MV_MultiM_Click = 24;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_MultiM_Click = new DATA_REPORT_TYPE(24,_EMID_Secure_MV_MultiM_Click,"EMID_Secure_MV_MultiM_Click");
    
    
    public static final int _EMID_Secure_MV_MultiM_Enter = 25;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_MultiM_Enter = new DATA_REPORT_TYPE(25,_EMID_Secure_MV_MultiM_Enter,"EMID_Secure_MV_MultiM_Enter");
    
    public static final int _EMID_Secure_MV_PIC_Imp_OK = 26;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_PIC_Imp_OK = new DATA_REPORT_TYPE(26,_EMID_Secure_MV_PIC_Imp_OK,"EMID_Secure_MV_PIC_Imp_OK");
    
    public static final int _EMID_Secure_MV_Video_Imp_OK = 27;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Video_Imp_OK = new DATA_REPORT_TYPE(27,_EMID_Secure_MV_Video_Imp_OK,"EMID_Secure_MV_Video_Imp_OK");
    
    public static final int _EMID_Secure_MV_Audio_Imp_OK = 28;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Audio_Imp_OK = new DATA_REPORT_TYPE(28,_EMID_Secure_MV_Audio_Imp_OK,"EMID_Secure_MV_Audio_Imp_OK");
    
    public static final int _EMID_Secure_MV_PIC_Exp_OK = 29;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_PIC_Exp_OK = new DATA_REPORT_TYPE(29,_EMID_Secure_MV_PIC_Exp_OK,"EMID_Secure_MV_PIC_Exp_OK");
    
    public static final int _EMID_Secure_MV_Video_Exp_OK = 30;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Video_Exp_OK = new DATA_REPORT_TYPE(30,_EMID_Secure_MV_Video_Exp_OK,"EMID_Secure_MV_Video_Exp_OK");
    
    public static final int _EMID_Secure_MV_Audio_Exp_OK = 31;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Audio_Exp_OK = new DATA_REPORT_TYPE(31,_EMID_Secure_MV_Audio_Exp_OK,"EMID_Secure_MV_Audio_Exp_OK");
    
    public static final int _EMID_Secure_MV_Del_Origin_OK = 32;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Del_Origin_OK = new DATA_REPORT_TYPE(32,_EMID_Secure_MV_Del_Origin_OK,"EMID_Secure_MV_Del_Origin_OK");
    
    public static final int _EMID_Secure_PRIVATE_PROTECT_password_setting = 33;
    public static final DATA_REPORT_TYPE EMID_Secure_PRIVATE_PROTECT_password_setting = new DATA_REPORT_TYPE(33,_EMID_Secure_PRIVATE_PROTECT_password_setting,"EMID_Secure_PRIVATE_PROTECT_password_setting");
    
    public static final int _EMID_Secure_MV_Setting_Modify = 34;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_Setting_Modify = new DATA_REPORT_TYPE(34,_EMID_Secure_MV_Setting_Modify,"EMID_Secure_MV_Setting_Modify");
    
    public static final int _EMID_Secure_Boost_INTO_VIP = 35;
    public static final DATA_REPORT_TYPE EMID_Secure_Boost_INTO_VIP = new DATA_REPORT_TYPE(35,_EMID_Secure_Boost_INTO_VIP,"EMID_Secure_Boost_INTO_VIP");
    
    
    public static final int _EMID_Secure_Virus_INTO_VIP = 36;
    public static final DATA_REPORT_TYPE EMID_Secure_Virus_INTO_VIP = new DATA_REPORT_TYPE(36,_EMID_Secure_Virus_INTO_VIP,"EMID_Secure_Virus_INTO_VIP");
    
    public static final int _EMID_Secure_MV_INTO_VIP = 37;
    public static final DATA_REPORT_TYPE EMID_Secure_MV_INTO_VIP = new DATA_REPORT_TYPE(37,_EMID_Secure_MV_INTO_VIP,"EMID_Secure_MV_INTO_VIP");
    
    public static final int _EMID_Secure_VIP_Get_Click = 38;
    public static final DATA_REPORT_TYPE EMID_Secure_VIP_Get_Click = new DATA_REPORT_TYPE(38,_EMID_Secure_VIP_Get_Click,"EMID_Secure_VIP_Get_Click");
    
    public static final int _EMID_Secure_Trial_Get_Click = 39;
    public static final DATA_REPORT_TYPE EMID_Secure_Trial_Get_Click = new DATA_REPORT_TYPE(39,_EMID_Secure_Trial_Get_Click,"EMID_Secure_Trial_Get_Click");
    
    public static final int _EMID_Secure_Trial_Get_SMS_Share = 40;
    public static final DATA_REPORT_TYPE EMID_Secure_Trial_Get_SMS_Share = new DATA_REPORT_TYPE(40,_EMID_Secure_Trial_Get_SMS_Share,"EMID_Secure_Trial_Get_SMS_Share");
    
    public static final int _EMID_Secure_Trial_Obtain = 41;
    public static final DATA_REPORT_TYPE EMID_Secure_Trial_Obtain = new DATA_REPORT_TYPE(41,_EMID_Secure_Trial_Obtain,"EMID_Secure_Trial_Obtain");
    

    public static final int _EMID_Secure_VIP_Pay_Success = 42;
    public static final DATA_REPORT_TYPE EMID_Secure_VIP_Pay_Success = new DATA_REPORT_TYPE(42,_EMID_Secure_VIP_Pay_Success,"EMID_Secure_VIP_Pay_Success");
    
    public static final int _EMID_Secure_MAINVIEW_Into_Menu_Setting = 43;
    public static final DATA_REPORT_TYPE EMID_Secure_MAINVIEW_Into_Menu_Setting = new DATA_REPORT_TYPE(43,_EMID_Secure_MAINVIEW_Into_Menu_Setting,"EMID_Secure_MAINVIEW_Into_Menu_Setting");
    
    public static final int _EMID_Secure_Menu_Setting_SMS_Share = 44;
    public static final DATA_REPORT_TYPE EMID_Secure_Menu_Setting_SMS_Share = new DATA_REPORT_TYPE(44,_EMID_Secure_Menu_Setting_SMS_Share,"EMID_Secure_Menu_Setting_SMS_Share");
    
    
    public static DATA_REPORT_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static DATA_REPORT_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private DATA_REPORT_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
