// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class DRFeatureClick extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2043843632037905779L;

	public String className()
    {
        return "com.tencent.onesecurity.util.jce.DRFeatureClick";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.util.jce.DRFeatureClick";
    }

    public java.util.ArrayList<Long> click = null;

    public java.util.ArrayList<Long> getClick()
    {
        return click;
    }

    public void  setClick(java.util.ArrayList<Long> click)
    {
        this.click = click;
    }

    public DRFeatureClick()
    {
        setClick(click);
    }

    public DRFeatureClick(java.util.ArrayList<Long> click)
    {
        setClick(click);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DRFeatureClick t = (DRFeatureClick) o;
        return (
            com.qq.taf.jce.JceUtil.equals(click, t.click) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(click, 0);
    }

    static java.util.ArrayList<Long> cache_click;

    @SuppressWarnings("unchecked")
	public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_click)
        {
            cache_click = new java.util.ArrayList<Long>();
            Long __var_4 = 0L;
            ((java.util.ArrayList<Long>)cache_click).add(__var_4);
        }
        setClick((java.util.ArrayList<Long>) _is.read(cache_click, 0, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(click, "click");
    }

}

