// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class DRUserInfoType extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2496246112450618730L;

	public String className()
    {
        return "com.tencent.onesecurity.util.jce.DRUserInfoType";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.util.jce.DRUserInfoType";
    }

    public int type = 0;

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public DRUserInfoType()
    {
        setType(type);
    }

    public DRUserInfoType(int type)
    {
        setType(type);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DRUserInfoType t = (DRUserInfoType) o;
        return (
            com.qq.taf.jce.JceUtil.equals(type, t.type) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
    }

    static int cache_type;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setType((int) _is.read(type, 0, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
    }

}

