// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class FLAG_USER_FIRST_INS
{
    private static FLAG_USER_FIRST_INS[] __values = new FLAG_USER_FIRST_INS[2];
    private int __value;
    private String __T = new String();

    public static final int _FLAG_FIRST_INS_MASK = 4097;
    public static final FLAG_USER_FIRST_INS FLAG_FIRST_INS_MASK = new FLAG_USER_FIRST_INS(0,_FLAG_FIRST_INS_MASK,"FLAG_FIRST_INS_MASK");
    public static final int _FLAG_NOT_FIRST_INS_MASK = 4098;
    public static final FLAG_USER_FIRST_INS FLAG_NOT_FIRST_INS_MASK = new FLAG_USER_FIRST_INS(1,_FLAG_NOT_FIRST_INS_MASK,"FLAG_NOT_FIRST_INS_MASK");

    public static FLAG_USER_FIRST_INS convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static FLAG_USER_FIRST_INS convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private FLAG_USER_FIRST_INS(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
