// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(14).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class HolidayPicInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4395509644886077604L;

	public String className()
    {
        return "QQD.HolidayPicInfo";
    }

    public String fullClassName()
    {
        return "QQD.HolidayPicInfo";
    }

    public long startDateTime = 0;

    public long endDateTime = 0;

    public String picUrl = "";

    public long getStartDateTime()
    {
        return startDateTime;
    }

    public void  setStartDateTime(long startDateTime)
    {
        this.startDateTime = startDateTime;
    }

    public long getEndDateTime()
    {
        return endDateTime;
    }

    public void  setEndDateTime(long endDateTime)
    {
        this.endDateTime = endDateTime;
    }

    public String getPicUrl()
    {
        return picUrl;
    }

    public void  setPicUrl(String picUrl)
    {
        this.picUrl = picUrl;
    }

    public HolidayPicInfo()
    {
        setStartDateTime(startDateTime);
        setEndDateTime(endDateTime);
        setPicUrl(picUrl);
    }

    public HolidayPicInfo(long startDateTime, long endDateTime, String picUrl)
    {
        setStartDateTime(startDateTime);
        setEndDateTime(endDateTime);
        setPicUrl(picUrl);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        HolidayPicInfo t = (HolidayPicInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(startDateTime, t.startDateTime) && 
            com.qq.taf.jce.JceUtil.equals(endDateTime, t.endDateTime) && 
            com.qq.taf.jce.JceUtil.equals(picUrl, t.picUrl) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(startDateTime, 0);
        _os.write(endDateTime, 1);
        _os.write(picUrl, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setStartDateTime((long) _is.read(startDateTime, 0, true));

        setEndDateTime((long) _is.read(endDateTime, 1, true));

        setPicUrl( _is.readString(2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(startDateTime, "startDateTime");
        _ds.display(endDateTime, "endDateTime");
        _ds.display(picUrl, "picUrl");
    }

}

