// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(14).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class HolidayPicInfoHolder
{
    public HolidayPicInfoHolder()
    {
    }
    public HolidayPicInfoHolder(HolidayPicInfo value)
    {
        this.value = value;
    }

    public HolidayPicInfo value;
}
