package com.tencent.onesecurity.util.jce;

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************


public final class notification_type
{
    private static notification_type[] __values = new notification_type[3];
    private int __value;
    private String __T = new String();

    public static final int _TYPE_TIPS = 0;
    public static final notification_type TYPE_TIPS = new notification_type(0,_TYPE_TIPS,"TYPE_TIPS");
    public static final int _TYPE_PLUGIN = 1;
    public static final notification_type TYPE_PLUGIN = new notification_type(1,_TYPE_PLUGIN,"TYPE_PLUGIN");
    public static final int _TYPE_CONFIG = 2;
    public static final notification_type TYPE_CONFIG = new notification_type(2,_TYPE_CONFIG,"TYPE_CONFIG");

    public static notification_type convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static notification_type convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private notification_type(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
