package com.tencent.onesecurity.util.jce;

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************



public final class PluginTaf extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7648105781225511597L;

	public String className()
    {
        return "QQD.PluginTaf";
    }

    public String fullClassName()
    {
        return "QQD.PluginTaf";
    }

    public String Id = "";

    public long DisplaySart = 0;

    public long DisplayEnd = 0;

    public long EffectiveTime = 0;

    public long FailTime = 0;

    public String Title = "";

    public String icon = "";

    public int type = 0;

    public String data = "";

    public String getId()
    {
        return Id;
    }

    public void  setId(String Id)
    {
        this.Id = Id;
    }

    public long getDisplaySart()
    {
        return DisplaySart;
    }

    public void  setDisplaySart(long DisplaySart)
    {
        this.DisplaySart = DisplaySart;
    }

    public long getDisplayEnd()
    {
        return DisplayEnd;
    }

    public void  setDisplayEnd(long DisplayEnd)
    {
        this.DisplayEnd = DisplayEnd;
    }

    public long getEffectiveTime()
    {
        return EffectiveTime;
    }

    public void  setEffectiveTime(long EffectiveTime)
    {
        this.EffectiveTime = EffectiveTime;
    }

    public long getFailTime()
    {
        return FailTime;
    }

    public void  setFailTime(long FailTime)
    {
        this.FailTime = FailTime;
    }

    public String getTitle()
    {
        return Title;
    }

    public void  setTitle(String Title)
    {
        this.Title = Title;
    }

    public String getIcon()
    {
        return icon;
    }

    public void  setIcon(String icon)
    {
        this.icon = icon;
    }

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public String getData()
    {
        return data;
    }

    public void  setData(String data)
    {
        this.data = data;
    }

    public PluginTaf()
    {
        setId(Id);
        setDisplaySart(DisplaySart);
        setDisplayEnd(DisplayEnd);
        setEffectiveTime(EffectiveTime);
        setFailTime(FailTime);
        setTitle(Title);
        setIcon(icon);
        setType(type);
        setData(data);
    }

    public PluginTaf(String Id, long DisplaySart, long DisplayEnd, long EffectiveTime, long FailTime, String Title, String icon, int type, String data)
    {
        setId(Id);
        setDisplaySart(DisplaySart);
        setDisplayEnd(DisplayEnd);
        setEffectiveTime(EffectiveTime);
        setFailTime(FailTime);
        setTitle(Title);
        setIcon(icon);
        setType(type);
        setData(data);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PluginTaf t = (PluginTaf) o;
        return (
            com.qq.taf.jce.JceUtil.equals(Id, t.Id) && 
            com.qq.taf.jce.JceUtil.equals(DisplaySart, t.DisplaySart) && 
            com.qq.taf.jce.JceUtil.equals(DisplayEnd, t.DisplayEnd) && 
            com.qq.taf.jce.JceUtil.equals(EffectiveTime, t.EffectiveTime) && 
            com.qq.taf.jce.JceUtil.equals(FailTime, t.FailTime) && 
            com.qq.taf.jce.JceUtil.equals(Title, t.Title) && 
            com.qq.taf.jce.JceUtil.equals(icon, t.icon) && 
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(data, t.data) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(Id, 0);
        _os.write(DisplaySart, 1);
        _os.write(DisplayEnd, 2);
        _os.write(EffectiveTime, 3);
        _os.write(FailTime, 4);
        _os.write(Title, 5);
        _os.write(icon, 6);
        _os.write(type, 7);
        _os.write(data, 8);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setId( _is.readString(0, true));

        setDisplaySart((long) _is.read(DisplaySart, 1, true));

        setDisplayEnd((long) _is.read(DisplayEnd, 2, true));

        setEffectiveTime((long) _is.read(EffectiveTime, 3, true));

        setFailTime((long) _is.read(FailTime, 4, true));

        setTitle( _is.readString(5, true));

        setIcon( _is.readString(6, true));

        setType((int) _is.read(type, 7, true));

        setData( _is.readString(8, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(Id, "Id");
        _ds.display(DisplaySart, "DisplaySart");
        _ds.display(DisplayEnd, "DisplayEnd");
        _ds.display(EffectiveTime, "EffectiveTime");
        _ds.display(FailTime, "FailTime");
        _ds.display(Title, "Title");
        _ds.display(icon, "icon");
        _ds.display(type, "type");
        _ds.display(data, "data");
    }

}

