// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class PromotionInfo extends com.qq.taf.jce.JceStruct
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4664242148156651516L;

	public String className()
    {
        return "QQD.PromotionInfo";
    }

    public String fullClassName()
    {
        return "com.qq.QQD.PromotionInfo";
    }

    public String packageName = "";

    public String campaignSource = "";

    public String campaignMedium = "";

    public String campaignTerm = "";

    public String campaignContent = "";

    public String campaignName = "";

    public String getPackageName()
    {
        return packageName;
    }

    public void  setPackageName(String packageName)
    {
        this.packageName = packageName;
    }

    public String getCampaignSource()
    {
        return campaignSource;
    }

    public void  setCampaignSource(String campaignSource)
    {
        this.campaignSource = campaignSource;
    }

    public String getCampaignMedium()
    {
        return campaignMedium;
    }

    public void  setCampaignMedium(String campaignMedium)
    {
        this.campaignMedium = campaignMedium;
    }

    public String getCampaignTerm()
    {
        return campaignTerm;
    }

    public void  setCampaignTerm(String campaignTerm)
    {
        this.campaignTerm = campaignTerm;
    }

    public String getCampaignContent()
    {
        return campaignContent;
    }

    public void  setCampaignContent(String campaignContent)
    {
        this.campaignContent = campaignContent;
    }

    public String getCampaignName()
    {
        return campaignName;
    }

    public void  setCampaignName(String campaignName)
    {
        this.campaignName = campaignName;
    }

    public PromotionInfo()
    {
        setPackageName(packageName);
        setCampaignSource(campaignSource);
        setCampaignMedium(campaignMedium);
        setCampaignTerm(campaignTerm);
        setCampaignContent(campaignContent);
        setCampaignName(campaignName);
    }

    public PromotionInfo(String packageName, String campaignSource, String campaignMedium, String campaignTerm, String campaignContent, String campaignName)
    {
        setPackageName(packageName);
        setCampaignSource(campaignSource);
        setCampaignMedium(campaignMedium);
        setCampaignTerm(campaignTerm);
        setCampaignContent(campaignContent);
        setCampaignName(campaignName);
    }

    public boolean equals(Object o)
    {
        PromotionInfo t = (PromotionInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(packageName, t.packageName) && 
            com.qq.taf.jce.JceUtil.equals(campaignSource, t.campaignSource) && 
            com.qq.taf.jce.JceUtil.equals(campaignMedium, t.campaignMedium) && 
            com.qq.taf.jce.JceUtil.equals(campaignTerm, t.campaignTerm) && 
            com.qq.taf.jce.JceUtil.equals(campaignContent, t.campaignContent) && 
            com.qq.taf.jce.JceUtil.equals(campaignName, t.campaignName) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(packageName, 0);
        _os.write(campaignSource, 1);
        _os.write(campaignMedium, 2);
        _os.write(campaignTerm, 3);
        _os.write(campaignContent, 4);
        _os.write(campaignName, 5);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setPackageName( _is.readString(0, true));

        setCampaignSource( _is.readString(1, true));

        setCampaignMedium( _is.readString(2, true));

        setCampaignTerm( _is.readString(3, true));

        setCampaignContent( _is.readString(4, true));

        setCampaignName( _is.readString(5, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(packageName, "packageName");
        _ds.display(campaignSource, "campaignSource");
        _ds.display(campaignMedium, "campaignMedium");
        _ds.display(campaignTerm, "campaignTerm");
        _ds.display(campaignContent, "campaignContent");
        _ds.display(campaignName, "campaignName");
    }

}

