// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDHttpRequest.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class QQDHttpRequestStru<T> extends com.qq.taf.jce.JceStruct {

	private static final long serialVersionUID = 8025677944646193183L;

	public String className() {
		return "QQD.QQDHttpRequestStru";
	}

	public String fullClassName() {
		return "QQDHttpRequestStru";
	}

	public int req = 0;

	public T reqStruct = null;

	public int getReq() {
		return req;
	}

	public void setReq(int req) {
		this.req = req;
	}

	public void setReqStruct(T t) {
		this.reqStruct = t;
	}

	public QQDHttpRequestStru() {
		setReq(req);
		setReqStruct(reqStruct);
	}

	public QQDHttpRequestStru(int req, T reqStruct) {
		setReq(req);
		setReqStruct(reqStruct);
	}

	public boolean equals(Object o) {
		QQDHttpRequestStru<?> t = (QQDHttpRequestStru<?>) o;
		return (com.qq.taf.jce.JceUtil.equals(req, t.req) && com.qq.taf.jce.JceUtil
				.equals(reqStruct, t.reqStruct));
	}

	public java.lang.Object clone() {
		java.lang.Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException ex) {
			assert false; // impossible
		}
		return o;
	}

	public void writeTo(com.qq.taf.jce.JceOutputStream _os) {
		_os.write(req, 0);
		_os.write(reqStruct, 1);
	}

	

	public void readFrom(com.qq.taf.jce.JceInputStream _is) {
		setReq((int) _is.read(req, 0, true));
	}

	public void display(java.lang.StringBuilder _os, int _level) {
		com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os,
				_level);
		_ds.display(req, "req");
		_ds.display(reqStruct, "reqStruct");
	}

}
