// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(14).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class REQ
{
    private static REQ[] __values = new REQ[8];
    private int __value;
    private String __T = new String();

    public static final int _REQ_GetTimestamp = 1;
    public static final REQ REQ_GetTimestamp = new REQ(0,_REQ_GetTimestamp,"REQ_GetTimestamp");
    public static final int _REQ_ReportChannel = 2;
    public static final REQ REQ_ReportChannel = new REQ(1,_REQ_ReportChannel,"REQ_ReportChannel");
    public static final int _REQ_DataReport = 3;
    public static final REQ REQ_DataReport = new REQ(2,_REQ_DataReport,"REQ_DataReport");
    public static final int _REQ_NotificationCenter = 4;
    public static final REQ REQ_NotificationCenter = new REQ(3,_REQ_NotificationCenter,"REQ_NotificationCenter");
    public static final int _REQ_AppReport = 5;
    public static final REQ REQ_AppReport = new REQ(4,_REQ_AppReport,"REQ_AppReport");
    public static final int _REQ_DataReportNew = 6;
    public static final REQ REQ_DataReportNew = new REQ(5,_REQ_DataReportNew,"REQ_DataReportNew");
    public static final int _REQ_DataReportSingle = 7;
    public static final REQ REQ_DataReportSingle = new REQ(6,_REQ_DataReportSingle,"REQ_DataReportSingle");
    public static final int _REQ_GetHolidayPic = 8;
    public static final REQ REQ_GetHolidayPic = new REQ(7,_REQ_GetHolidayPic,"REQ_GetHolidayPic");

    public static REQ convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static REQ convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private REQ(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
