// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(11).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class ReqAppReport extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String className()
    {
        return "ReqAppReport";
    }

    public String fullClassName()
    {
        return "ReqAppReport";
    }

    public String imei = "";

    public java.util.ArrayList<AppInfo> appInfos = null;

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public java.util.ArrayList<AppInfo> getAppInfos()
    {
        return appInfos;
    }

    public void  setAppInfos(java.util.ArrayList<AppInfo> appInfos)
    {
        this.appInfos = appInfos;
    }

    public ReqAppReport()
    {
        setImei(imei);
        setAppInfos(appInfos);
    }

    public ReqAppReport(String imei, java.util.ArrayList<AppInfo> appInfos)
    {
        setImei(imei);
        setAppInfos(appInfos);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqAppReport t = (ReqAppReport) o;
        return (
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(appInfos, t.appInfos) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(imei, 0);
        _os.write(appInfos, 1);
    }

    static java.util.ArrayList<AppInfo> cache_appInfos;

    @SuppressWarnings("unchecked")
	public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setImei( _is.readString(0, true));

        if(null == cache_appInfos)
        {
            cache_appInfos = new java.util.ArrayList<AppInfo>();
            AppInfo __var_10 = new AppInfo();
            ((java.util.ArrayList<AppInfo>)cache_appInfos).add(__var_10);
        }
        setAppInfos((java.util.ArrayList<AppInfo>) _is.read(cache_appInfos, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(imei, "imei");
        _ds.display(appInfos, "appInfos");
    }

}

