// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class ReqGetTimestamp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 849676234986205258L;

	public String className()
    {
        return "com.tencent.onesecurity.util.jce.ReqGetTimestamp";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.util.jce.ReqGetTimestamp";
    }

    public String format = "";

    public String getFormat()
    {
        return format;
    }

    public void  setFormat(String format)
    {
        this.format = format;
    }

    public ReqGetTimestamp()
    {
        setFormat(format);
    }

    public ReqGetTimestamp(String format)
    {
        setFormat(format);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqGetTimestamp t = (ReqGetTimestamp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(format, t.format) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(format, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setFormat( _is.readString(0, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(format, "format");
    }

}

