// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(14).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class ReqGetHolidayPic extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6463896787352228280L;

	public String className()
    {
        return "QQD.ReqGetHolidayPic";
    }

    public String fullClassName()
    {
        return "QQD.ReqGetHolidayPic";
    }

    public String lc = "";

    public String countryId = "XX";

    public int resolution = 0;

    public String getLc()
    {
        return lc;
    }

    public void  setLc(String lc)
    {
        this.lc = lc;
    }

    public String getCountryId()
    {
        return countryId;
    }

    public void  setCountryId(String countryId)
    {
        this.countryId = countryId;
    }

    public int getResolution()
    {
        return resolution;
    }

    public void  setResolution(int resolution)
    {
        this.resolution = resolution;
    }

    public ReqGetHolidayPic()
    {
        setLc(lc);
        setCountryId(countryId);
        setResolution(resolution);
    }

    public ReqGetHolidayPic(String lc, String countryId, int resolution)
    {
        setLc(lc);
        setCountryId(countryId);
        setResolution(resolution);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqGetHolidayPic t = (ReqGetHolidayPic) o;
        return (
            com.qq.taf.jce.JceUtil.equals(lc, t.lc) && 
            com.qq.taf.jce.JceUtil.equals(countryId, t.countryId) && 
            com.qq.taf.jce.JceUtil.equals(resolution, t.resolution) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(lc, 0);
        _os.write(countryId, 1);
        _os.write(resolution, 2);
    }

    static int cache_resolution;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setLc( _is.readString(0, true));

        setCountryId( _is.readString(1, true));

        setResolution((int) _is.read(resolution, 2, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(lc, "lc");
        _ds.display(countryId, "countryId");
        _ds.display(resolution, "resolution");
    }

}

