package com.tencent.onesecurity.util.jce;

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************


public final class ReqNotificationCenter extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3444765461355215115L;

	public String className()
    {
        return "QQD.ReqNotificationCenter";
    }

    public String fullClassName()
    {
        return "QQD.ReqNotificationCenter";
    }

    public StatInfo3G statInfo3G = null;

    public boolean isall = true;

    public StatInfo3G getStatInfo3G()
    {
        return statInfo3G;
    }

    public void  setStatInfo3G(StatInfo3G statInfo3G)
    {
        this.statInfo3G = statInfo3G;
    }

    public boolean getIsall()
    {
        return isall;
    }

    public void  setIsall(boolean isall)
    {
        this.isall = isall;
    }

    public ReqNotificationCenter()
    {
        setStatInfo3G(statInfo3G);
        setIsall(isall);
    }

    public ReqNotificationCenter(StatInfo3G statInfo3G, boolean isall)
    {
        setStatInfo3G(statInfo3G);
        setIsall(isall);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqNotificationCenter t = (ReqNotificationCenter) o;
        return (
            com.qq.taf.jce.JceUtil.equals(statInfo3G, t.statInfo3G) && 
            com.qq.taf.jce.JceUtil.equals(isall, t.isall) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(statInfo3G, 0);
        _os.write(isall, 1);
    }

    static StatInfo3G cache_statInfo3G;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_statInfo3G)
        {
            cache_statInfo3G = new StatInfo3G();
        }
        setStatInfo3G((StatInfo3G) _is.read(cache_statInfo3G, 0, true));

        setIsall((boolean) _is.read(isall, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(statInfo3G, "statInfo3G");
        _ds.display(isall, "isall");
    }

}

