// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class ReqReportChannel extends com.qq.taf.jce.JceStruct
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3990163945234126148L;

	public String className()
    {
        return "QQD.ReqReportChannel";
    }

    public String fullClassName()
    {
        return "com.qq.QQD.ReqReportChannel";
    }

    public com.tencent.onesecurity.util.jce.PromotionInfo promotionInfo = null;

    public com.tencent.onesecurity.util.jce.StatInfo3G statInfo = null;

    public com.tencent.onesecurity.util.jce.PromotionInfo getPromotionInfo()
    {
        return promotionInfo;
    }

    public void  setPromotionInfo(com.tencent.onesecurity.util.jce.PromotionInfo promotionInfo)
    {
        this.promotionInfo = promotionInfo;
    }

    public com.tencent.onesecurity.util.jce.StatInfo3G getStatInfo()
    {
        return statInfo;
    }

    public void  setStatInfo(com.tencent.onesecurity.util.jce.StatInfo3G statInfo)
    {
        this.statInfo = statInfo;
    }

    public ReqReportChannel()
    {
        setPromotionInfo(promotionInfo);
        setStatInfo(statInfo);
    }

    public ReqReportChannel(com.tencent.onesecurity.util.jce.PromotionInfo promotionInfo, com.tencent.onesecurity.util.jce.StatInfo3G statInfo)
    {
        setPromotionInfo(promotionInfo);
        setStatInfo(statInfo);
    }

    public boolean equals(Object o)
    {
        ReqReportChannel t = (ReqReportChannel) o;
        return (
            com.qq.taf.jce.JceUtil.equals(promotionInfo, t.promotionInfo) && 
            com.qq.taf.jce.JceUtil.equals(statInfo, t.statInfo) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(promotionInfo, 0);
        _os.write(statInfo, 1);
    }

    static com.tencent.onesecurity.util.jce.PromotionInfo cache_promotionInfo;
    static com.tencent.onesecurity.util.jce.StatInfo3G cache_statInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_promotionInfo)
        {
            cache_promotionInfo = new com.tencent.onesecurity.util.jce.PromotionInfo();
        }
        setPromotionInfo((com.tencent.onesecurity.util.jce.PromotionInfo) _is.read(cache_promotionInfo, 0, true));

        if(null == cache_statInfo)
        {
            cache_statInfo = new com.tencent.onesecurity.util.jce.StatInfo3G();
        }
        setStatInfo((com.tencent.onesecurity.util.jce.StatInfo3G) _is.read(cache_statInfo, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(promotionInfo, "promotionInfo");
        _ds.display(statInfo, "statInfo");
    }

}

