// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RespReportChannel extends com.qq.taf.jce.JceStruct
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3044846102901564238L;

	public String className()
    {
        return "QQD.RespReportChannel";
    }

    public String fullClassName()
    {
        return "com.qq.QQD.RespReportChannel";
    }

    public int retVal = 0;

    public int installCount = 0;

    public int getRetVal()
    {
        return retVal;
    }

    public void  setRetVal(int retVal)
    {
        this.retVal = retVal;
    }

    public int getInstallCount()
    {
        return installCount;
    }

    public void  setInstallCount(int installCount)
    {
        this.installCount = installCount;
    }

    public RespReportChannel()
    {
        setRetVal(retVal);
        setInstallCount(installCount);
    }

    public RespReportChannel(int retVal, int installCount)
    {
        setRetVal(retVal);
        setInstallCount(installCount);
    }

    public boolean equals(Object o)
    {
        RespReportChannel t = (RespReportChannel) o;
        return (
            com.qq.taf.jce.JceUtil.equals(retVal, t.retVal) && 
            com.qq.taf.jce.JceUtil.equals(installCount, t.installCount) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(retVal, 0);
        _os.write(installCount, 1);
    }

    static int cache_retVal;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setRetVal((int) _is.read(retVal, 0, true));

        setInstallCount((int) _is.read(installCount, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(retVal, "retVal");
        _ds.display(installCount, "installCount");
    }

}

