// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RespGetTimestamp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4893701812452127410L;

	public String className()
    {
        return "com.tencent.onesecurity.util.jce.RespGetTimestamp";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.util.jce.RespGetTimestamp";
    }

    public long timestamp = 0;

    public long getTimestamp()
    {
        return timestamp;
    }

    public void  setTimestamp(long timestamp)
    {
        this.timestamp = timestamp;
    }

    public RespGetTimestamp()
    {
        setTimestamp(timestamp);
    }

    public RespGetTimestamp(long timestamp)
    {
        setTimestamp(timestamp);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RespGetTimestamp t = (RespGetTimestamp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(timestamp, t.timestamp) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(timestamp, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setTimestamp((long) _is.read(timestamp, 0, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(timestamp, "timestamp");
    }

}

