// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(11).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RespAppReport extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String className()
    {
        return "QQD.RespAppReport";
    }

    public String fullClassName()
    {
        return "QQD.RespAppReport";
    }

    public int replyCode = 0;

    public String msg = "";

    public int getReplyCode()
    {
        return replyCode;
    }

    public void  setReplyCode(int replyCode)
    {
        this.replyCode = replyCode;
    }

    public String getMsg()
    {
        return msg;
    }

    public void  setMsg(String msg)
    {
        this.msg = msg;
    }

    public RespAppReport()
    {
        setReplyCode(replyCode);
        setMsg(msg);
    }

    public RespAppReport(int replyCode, String msg)
    {
        setReplyCode(replyCode);
        setMsg(msg);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RespAppReport t = (RespAppReport) o;
        return (
            com.qq.taf.jce.JceUtil.equals(replyCode, t.replyCode) && 
            com.qq.taf.jce.JceUtil.equals(msg, t.msg) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(replyCode, 0);
        if (null != msg)
        {
            _os.write(msg, 1);
        }
    }

    static int cache_replyCode;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setReplyCode((int) _is.read(replyCode, 0, true));

        setMsg( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(replyCode, "replyCode");
        _ds.display(msg, "msg");
    }

}

