// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(10).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RESP
{
    private static RESP[] __values = new RESP[7];
    private int __value;
    private String __T = new String();

    public static final int _RESP_GetTimestamp = 10001;
    public static final RESP RESP_GetTimestamp = new RESP(0,_RESP_GetTimestamp,"RESP_GetTimestamp");
    public static final int _RESP_ReportChannel = 10002;
    public static final RESP RESP_ReportChannel = new RESP(1,_RESP_ReportChannel,"RESP_ReportChannel");
    public static final int _RESP_DataReport = 10003;
    public static final RESP RESP_DataReport = new RESP(2,_RESP_DataReport,"RESP_DataReport");
    public static final int _RESP_NotificationCenter = 10004;
    public static final RESP RESP_NotificationCenter = new RESP(3,_RESP_NotificationCenter,"RESP_NotificationCenter");
    public static final int _RESP_AppReport = 10005;
    public static final RESP RESP_AppReport = new RESP(4,_RESP_AppReport,"RESP_AppReport");
    public static final int _RESP_DataReportNew = 10006;
    public static final RESP RESP_DataReportNew = new RESP(5,_RESP_DataReportNew,"RESP_DataReportNew");
    public static final int _RESP_DataReportSingle = 10007;
    public static final RESP RESP_DataReportSingle = new RESP(6,_RESP_DataReportSingle,"RESP_DataReportSingle");

    public static RESP convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static RESP convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private RESP(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
