package com.tencent.onesecurity.util.jce;

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************


public final class RespNotificationCenter extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2834806805626999128L;

	public String className()
    {
        return "QQD.RespNotificationCenter";
    }

    public String fullClassName()
    {
        return "QQD.RespNotificationCenter";
    }

    public int retVal = 0;

    public String errmsg = "";

    public java.util.ArrayList<TipsTaf> tipsData = null;

    public java.util.ArrayList<ConfigTaf> configData = null;

    public java.util.ArrayList<PluginTaf> pluginData = null;

    public int getRetVal()
    {
        return retVal;
    }

    public void  setRetVal(int retVal)
    {
        this.retVal = retVal;
    }

    public String getErrmsg()
    {
        return errmsg;
    }

    public void  setErrmsg(String errmsg)
    {
        this.errmsg = errmsg;
    }

    public java.util.ArrayList<TipsTaf> getTipsData()
    {
        return tipsData;
    }

    public void  setTipsData(java.util.ArrayList<TipsTaf> tipsData)
    {
        this.tipsData = tipsData;
    }

    public java.util.ArrayList<ConfigTaf> getConfigData()
    {
        return configData;
    }

    public void  setConfigData(java.util.ArrayList<ConfigTaf> configData)
    {
        this.configData = configData;
    }

    public java.util.ArrayList<PluginTaf> getPluginData()
    {
        return pluginData;
    }

    public void  setPluginData(java.util.ArrayList<PluginTaf> pluginData)
    {
        this.pluginData = pluginData;
    }

    public RespNotificationCenter()
    {
        setRetVal(retVal);
        setErrmsg(errmsg);
        setTipsData(tipsData);
        setConfigData(configData);
        setPluginData(pluginData);
    }

    public RespNotificationCenter(int retVal, String errmsg, java.util.ArrayList<TipsTaf> tipsData, java.util.ArrayList<ConfigTaf> configData, java.util.ArrayList<PluginTaf> pluginData)
    {
        setRetVal(retVal);
        setErrmsg(errmsg);
        setTipsData(tipsData);
        setConfigData(configData);
        setPluginData(pluginData);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RespNotificationCenter t = (RespNotificationCenter) o;
        return (
            com.qq.taf.jce.JceUtil.equals(retVal, t.retVal) && 
            com.qq.taf.jce.JceUtil.equals(errmsg, t.errmsg) && 
            com.qq.taf.jce.JceUtil.equals(tipsData, t.tipsData) && 
            com.qq.taf.jce.JceUtil.equals(configData, t.configData) && 
            com.qq.taf.jce.JceUtil.equals(pluginData, t.pluginData) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(retVal, 0);
        _os.write(errmsg, 1);
        if (null != tipsData)
        {
            _os.write(tipsData, 2);
        }
        if (null != configData)
        {
            _os.write(configData, 3);
        }
        if (null != pluginData)
        {
            _os.write(pluginData, 4);
        }
    }

    static int cache_retVal;
    static java.util.ArrayList<TipsTaf> cache_tipsData;
    static java.util.ArrayList<ConfigTaf> cache_configData;
    static java.util.ArrayList<PluginTaf> cache_pluginData;

    @SuppressWarnings("unchecked")
	public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setRetVal((int) _is.read(retVal, 0, true));

        setErrmsg( _is.readString(1, true));

        if(null == cache_tipsData)
        {
            cache_tipsData = new java.util.ArrayList<TipsTaf>();
            TipsTaf __var_7 = new TipsTaf();
            ((java.util.ArrayList<TipsTaf>)cache_tipsData).add(__var_7);
        }
        setTipsData((java.util.ArrayList<TipsTaf>) _is.read(cache_tipsData, 2, false));

        if(null == cache_configData)
        {
            cache_configData = new java.util.ArrayList<ConfigTaf>();
            ConfigTaf __var_8 = new ConfigTaf();
            ((java.util.ArrayList<ConfigTaf>)cache_configData).add(__var_8);
        }
        setConfigData((java.util.ArrayList<ConfigTaf>) _is.read(cache_configData, 3, false));

        if(null == cache_pluginData)
        {
            cache_pluginData = new java.util.ArrayList<PluginTaf>();
            PluginTaf __var_9 = new PluginTaf();
            ((java.util.ArrayList<PluginTaf>)cache_pluginData).add(__var_9);
        }
        setPluginData((java.util.ArrayList<PluginTaf>) _is.read(cache_pluginData, 4, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(retVal, "retVal");
        _ds.display(errmsg, "errmsg");
        _ds.display(tipsData, "tipsData");
        _ds.display(configData, "configData");
        _ds.display(pluginData, "pluginData");
    }

}

