// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(4).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RespDataReportNew extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String className()
    {
        return "QQD.RespDataReportNew";
    }

    public String fullClassName()
    {
        return "QQD.RespDataReportNew";
    }

    public int retVal = 0;

    public int getRetVal()
    {
        return retVal;
    }

    public void  setRetVal(int retVal)
    {
        this.retVal = retVal;
    }

    public RespDataReportNew()
    {
        setRetVal(retVal);
    }

    public RespDataReportNew(int retVal)
    {
        setRetVal(retVal);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RespDataReportNew t = (RespDataReportNew) o;
        return (
            com.qq.taf.jce.JceUtil.equals(retVal, t.retVal) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(retVal, 0);
    }

    static int cache_retVal;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setRetVal((int) _is.read(retVal, 0, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(retVal, "retVal");
    }

}

