// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(14).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RespGetHolidayPic extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = -293989838709269958L;

	public String className()
    {
        return "QQD.RespGetHolidayPic";
    }

    public String fullClassName()
    {
        return "QQD.RespGetHolidayPic";
    }

    public int replyCode = 0;

    public HolidayPicInfo holidayPicInfo = null;

    public int getReplyCode()
    {
        return replyCode;
    }

    public void  setReplyCode(int replyCode)
    {
        this.replyCode = replyCode;
    }

    public HolidayPicInfo getHolidayPicInfo()
    {
        return holidayPicInfo;
    }

    public void  setHolidayPicInfo(HolidayPicInfo holidayPicInfo)
    {
        this.holidayPicInfo = holidayPicInfo;
    }

    public RespGetHolidayPic()
    {
        setReplyCode(replyCode);
        setHolidayPicInfo(holidayPicInfo);
    }

    public RespGetHolidayPic(int replyCode, HolidayPicInfo holidayPicInfo)
    {
        setReplyCode(replyCode);
        setHolidayPicInfo(holidayPicInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RespGetHolidayPic t = (RespGetHolidayPic) o;
        return (
            com.qq.taf.jce.JceUtil.equals(replyCode, t.replyCode) && 
            com.qq.taf.jce.JceUtil.equals(holidayPicInfo, t.holidayPicInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(replyCode, 0);
        if (null != holidayPicInfo)
        {
            _os.write(holidayPicInfo, 1);
        }
    }

    static int cache_replyCode;
    static HolidayPicInfo cache_holidayPicInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setReplyCode((int) _is.read(replyCode, 0, true));

        if(null == cache_holidayPicInfo)
        {
            cache_holidayPicInfo = new HolidayPicInfo();
        }
        setHolidayPicInfo((HolidayPicInfo) _is.read(cache_holidayPicInfo, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(replyCode, "replyCode");
        _ds.display(holidayPicInfo, "holidayPicInfo");
    }

}

