// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class RET_VAL
{
    private static RET_VAL[] __values = new RET_VAL[2];
    private int __value;
    private String __T = new String();

    public static final int _RET_Fail = 0;
    public static final RET_VAL RET_Fail = new RET_VAL(0,_RET_Fail,"RET_Fail");
    public static final int _RET_Success = 1;
    public static final RET_VAL RET_Success = new RET_VAL(1,_RET_Success,"RET_Success");

    public static RET_VAL convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static RET_VAL convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private RET_VAL(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
