// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.1 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class StatInfo3G extends com.qq.taf.jce.JceStruct
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7522506629473744901L;

	public String className()
    {
        return "com.tencent.onesecurity.util.jce.StatInfo3G";
    }

    public String fullClassName()
    {
        return "com.tencent.onesecurity.util.jce.StatInfo3G";
    }

    public int appId = 0;

    public String lc = "";

    public int channelId = 0;

    public String phoneNumber = "";

    public String imei = "";

    public String imsi = "";

    public String ua = "";

    public String phoneType = "";

    public String subPlatform = "";

    public boolean isbuildin = true;

    public boolean isroot = true;

    public String country = "";

    public int userType = 0;

    public int promotionId = 0;

    public int getAppId()
    {
        return appId;
    }

    public void  setAppId(int appId)
    {
        this.appId = appId;
    }

    public String getLc()
    {
        return lc;
    }

    public void  setLc(String lc)
    {
        this.lc = lc;
    }

    public int getChannelId()
    {
        return channelId;
    }

    public void  setChannelId(int channelId)
    {
        this.channelId = channelId;
    }

    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    public void  setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getImsi()
    {
        return imsi;
    }

    public void  setImsi(String imsi)
    {
        this.imsi = imsi;
    }

    public String getUa()
    {
        return ua;
    }

    public void  setUa(String ua)
    {
        this.ua = ua;
    }

    public String getPhoneType()
    {
        return phoneType;
    }

    public void  setPhoneType(String phoneType)
    {
        this.phoneType = phoneType;
    }

    public String getSubPlatform()
    {
        return subPlatform;
    }

    public void  setSubPlatform(String subPlatform)
    {
        this.subPlatform = subPlatform;
    }

    public boolean getIsbuildin()
    {
        return isbuildin;
    }

    public void  setIsbuildin(boolean isbuildin)
    {
        this.isbuildin = isbuildin;
    }

    public boolean getIsroot()
    {
        return isroot;
    }

    public void  setIsroot(boolean isroot)
    {
        this.isroot = isroot;
    }

    public String getCountry()
    {
        return country;
    }

    public void  setCountry(String country)
    {
        this.country = country;
    }

    public int getUserType()
    {
        return userType;
    }

    public void  setUserType(int userType)
    {
        this.userType = userType;
    }

    public int getPromotionId()
    {
        return promotionId;
    }

    public void  setPromotionId(int promotionId)
    {
        this.promotionId = promotionId;
    }

    public StatInfo3G()
    {
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setPhoneNumber(phoneNumber);
        setImei(imei);
        setImsi(imsi);
        setUa(ua);
        setPhoneType(phoneType);
        setSubPlatform(subPlatform);
        setIsbuildin(isbuildin);
        setIsroot(isroot);
        setCountry(country);
        setUserType(userType);
        setPromotionId(promotionId);
    }

    public StatInfo3G(int appId, String lc, int channelId, String phoneNumber, String imei, String imsi, String ua, String phoneType, String subPlatform, boolean isbuildin, boolean isroot, String country, int userType, int promotionId)
    {
        setAppId(appId);
        setLc(lc);
        setChannelId(channelId);
        setPhoneNumber(phoneNumber);
        setImei(imei);
        setImsi(imsi);
        setUa(ua);
        setPhoneType(phoneType);
        setSubPlatform(subPlatform);
        setIsbuildin(isbuildin);
        setIsroot(isroot);
        setCountry(country);
        setUserType(userType);
        setPromotionId(promotionId);
    }

    public boolean equals(Object o)
    {
        StatInfo3G t = (StatInfo3G) o;
        return (
            com.qq.taf.jce.JceUtil.equals(appId, t.appId) && 
            com.qq.taf.jce.JceUtil.equals(lc, t.lc) && 
            com.qq.taf.jce.JceUtil.equals(channelId, t.channelId) && 
            com.qq.taf.jce.JceUtil.equals(phoneNumber, t.phoneNumber) && 
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(imsi, t.imsi) && 
            com.qq.taf.jce.JceUtil.equals(ua, t.ua) && 
            com.qq.taf.jce.JceUtil.equals(phoneType, t.phoneType) && 
            com.qq.taf.jce.JceUtil.equals(subPlatform, t.subPlatform) && 
            com.qq.taf.jce.JceUtil.equals(isbuildin, t.isbuildin) && 
            com.qq.taf.jce.JceUtil.equals(isroot, t.isroot) && 
            com.qq.taf.jce.JceUtil.equals(country, t.country) && 
            com.qq.taf.jce.JceUtil.equals(userType, t.userType) && 
            com.qq.taf.jce.JceUtil.equals(promotionId, t.promotionId) );
    }

    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(appId, 0);
        _os.write(lc, 1);
        _os.write(channelId, 2);
        _os.write(phoneNumber, 3);
        _os.write(imei, 4);
        _os.write(imsi, 5);
        _os.write(ua, 6);
        _os.write(phoneType, 7);
        _os.write(subPlatform, 8);
        _os.write(isbuildin, 9);
        _os.write(isroot, 10);
        _os.write(country, 11);
        _os.write(userType, 12);
        _os.write(promotionId, 13);
    }

    static int cache_userType;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setAppId((int) _is.read(appId, 0, true));

        setLc( _is.readString(1, true));

        setChannelId((int) _is.read(channelId, 2, true));

        setPhoneNumber( _is.readString(3, true));

        setImei( _is.readString(4, true));

        setImsi( _is.readString(5, true));

        setUa( _is.readString(6, true));

        setPhoneType( _is.readString(7, true));

        setSubPlatform( _is.readString(8, true));

        setIsbuildin((boolean) _is.read(isbuildin, 9, true));

        setIsroot((boolean) _is.read(isroot, 10, true));

        setCountry( _is.readString(11, true));

        setUserType((int) _is.read(userType, 12, true));

        setPromotionId((int) _is.read(promotionId, 13, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(appId, "appId");
        _ds.display(lc, "lc");
        _ds.display(channelId, "channelId");
        _ds.display(phoneNumber, "phoneNumber");
        _ds.display(imei, "imei");
        _ds.display(imsi, "imsi");
        _ds.display(ua, "ua");
        _ds.display(phoneType, "phoneType");
        _ds.display(subPlatform, "subPlatform");
        _ds.display(isbuildin, "isbuildin");
        _ds.display(isroot, "isroot");
        _ds.display(country, "country");
        _ds.display(userType, "userType");
        _ds.display(promotionId, "promotionId");
    }

}

