package com.tencent.onesecurity.util.jce;

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol.jce'
// **********************************************************************


public final class TipsTaf extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8083692731110097948L;

	public String className()
    {
        return "QQD.TipsTaf";
    }

    public String fullClassName()
    {
        return "QQD.TipsTaf";
    }

    public String Id = "";

    public long DisplayBegin = 0;

    public long DisplayEnd = 0;

    public long EffectiveTime = 0;

    public long FailTime = 0;

    public String summary = "";

    public String Url = "";

    public String getId()
    {
        return Id;
    }

    public void  setId(String Id)
    {
        this.Id = Id;
    }

    public long getDisplayBegin()
    {
        return DisplayBegin;
    }

    public void  setDisplayBegin(long DisplayBegin)
    {
        this.DisplayBegin = DisplayBegin;
    }

    public long getDisplayEnd()
    {
        return DisplayEnd;
    }

    public void  setDisplayEnd(long DisplayEnd)
    {
        this.DisplayEnd = DisplayEnd;
    }

    public long getEffectiveTime()
    {
        return EffectiveTime;
    }

    public void  setEffectiveTime(long EffectiveTime)
    {
        this.EffectiveTime = EffectiveTime;
    }

    public long getFailTime()
    {
        return FailTime;
    }

    public void  setFailTime(long FailTime)
    {
        this.FailTime = FailTime;
    }

    public String getSummary()
    {
        return summary;
    }

    public void  setSummary(String summary)
    {
        this.summary = summary;
    }

    public String getUrl()
    {
        return Url;
    }

    public void  setUrl(String Url)
    {
        this.Url = Url;
    }

    public TipsTaf()
    {
        setId(Id);
        setDisplayBegin(DisplayBegin);
        setDisplayEnd(DisplayEnd);
        setEffectiveTime(EffectiveTime);
        setFailTime(FailTime);
        setSummary(summary);
        setUrl(Url);
    }

    public TipsTaf(String Id, long DisplayBegin, long DisplayEnd, long EffectiveTime, long FailTime, String summary, String Url)
    {
        setId(Id);
        setDisplayBegin(DisplayBegin);
        setDisplayEnd(DisplayEnd);
        setEffectiveTime(EffectiveTime);
        setFailTime(FailTime);
        setSummary(summary);
        setUrl(Url);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        TipsTaf t = (TipsTaf) o;
        return (
            com.qq.taf.jce.JceUtil.equals(Id, t.Id) && 
            com.qq.taf.jce.JceUtil.equals(DisplayBegin, t.DisplayBegin) && 
            com.qq.taf.jce.JceUtil.equals(DisplayEnd, t.DisplayEnd) && 
            com.qq.taf.jce.JceUtil.equals(EffectiveTime, t.EffectiveTime) && 
            com.qq.taf.jce.JceUtil.equals(FailTime, t.FailTime) && 
            com.qq.taf.jce.JceUtil.equals(summary, t.summary) && 
            com.qq.taf.jce.JceUtil.equals(Url, t.Url) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(Id, 0);
        _os.write(DisplayBegin, 1);
        _os.write(DisplayEnd, 2);
        _os.write(EffectiveTime, 3);
        _os.write(FailTime, 4);
        _os.write(summary, 5);
        _os.write(Url, 6);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setId( _is.readString(0, true));

        setDisplayBegin((long) _is.read(DisplayBegin, 1, true));

        setDisplayEnd((long) _is.read(DisplayEnd, 2, true));

        setEffectiveTime((long) _is.read(EffectiveTime, 3, true));

        setFailTime((long) _is.read(FailTime, 4, true));

        setSummary( _is.readString(5, true));

        setUrl( _is.readString(6, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(Id, "Id");
        _ds.display(DisplayBegin, "DisplayBegin");
        _ds.display(DisplayEnd, "DisplayEnd");
        _ds.display(EffectiveTime, "EffectiveTime");
        _ds.display(FailTime, "FailTime");
        _ds.display(summary, "summary");
        _ds.display(Url, "Url");
    }

}

