// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3 by WSRD Tencent.
// Generated from `QQDProtocol.jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class USER_INFO_TYPE
{
    private static USER_INFO_TYPE[] __values = new USER_INFO_TYPE[6];
    private int __value;
    private String __T = new String();

    public static final int _UI_OFF = 0;
    public static final USER_INFO_TYPE UI_OFF = new USER_INFO_TYPE(0,_UI_OFF,"UI_OFF");
    public static final int _UI_ON = 1;
    public static final USER_INFO_TYPE UI_ON = new USER_INFO_TYPE(1,_UI_ON,"UI_ON");
    public static final int _UI_EXPIRE = 2;
    public static final USER_INFO_TYPE UI_EXPIRE = new USER_INFO_TYPE(2,_UI_EXPIRE,"UI_EXPIRE");
    public static final int _UI_TRIAL = 3;
    public static final USER_INFO_TYPE UI_TRIAL = new USER_INFO_TYPE(3,_UI_TRIAL,"UI_TRIAL");
    public static final int _UI_EXCEPTION = 4;
    public static final USER_INFO_TYPE UI_EXCEPTION = new USER_INFO_TYPE(4,_UI_EXCEPTION,"UI_EXCEPTION");
    public static final int _UI_PRESET = 5;
    public static final USER_INFO_TYPE UI_PRESET = new USER_INFO_TYPE(5,_UI_PRESET,"UI_PRESET");

    public static USER_INFO_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static USER_INFO_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private USER_INFO_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
