// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.2 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/p_tonyli/QQDProtocol(11).jce'
// **********************************************************************

package com.tencent.onesecurity.util.jce;

public final class VirusInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String className()
    {
        return "QQD.VirusInfo";
    }

    public String fullClassName()
    {
        return "QQD.VirusInfo";
    }

    public String virusName = "";

    public int virusType = 0;

    public String getVirusName()
    {
        return virusName;
    }

    public void  setVirusName(String virusName)
    {
        this.virusName = virusName;
    }

    public int getVirusType()
    {
        return virusType;
    }

    public void  setVirusType(int virusType)
    {
        this.virusType = virusType;
    }

    public VirusInfo()
    {
        setVirusName(virusName);
        setVirusType(virusType);
    }

    public VirusInfo(String virusName, int virusType)
    {
        setVirusName(virusName);
        setVirusType(virusType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        VirusInfo t = (VirusInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(virusName, t.virusName) && 
            com.qq.taf.jce.JceUtil.equals(virusType, t.virusType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(virusName, 0);
        _os.write(virusType, 1);
    }

    static int cache_virusType;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setVirusName( _is.readString(0, true));

        setVirusType((int) _is.read(virusType, 1, true));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(virusName, "virusName");
        _ds.display(virusType, "virusType");
    }

}

